;;;; harness: bare
(require :asdf)
(unless (find-package :ql) (load (or (uiop:getenv "PAI_QUICKLISP_SETUP") "/opt/quicklisp/setup.lisp")))
(asdf:load-asd (merge-pathnames "../pai-context-graph.asd" *load-truename*))
(asdf:load-system :pai-context-graph)
(in-package :pai.context-graph)
(load (merge-pathnames "fixtures/context-graph-authority-fixtures.lisp" *load-truename*))
(defvar *authority-installation-checks* 0)
(defun ag-check (name value)
  (unless value (error "FAIL ~a" name))
  (incf *authority-installation-checks*) (format t "PASS ~a~%" name))
(multiple-value-bind (context grant view) (ar-fixture)
  (multiple-value-bind (partition policy participants) (as-fixture)
    (declare (ignore policy participants))
    (let* ((graph (make-context-graph (gethash "ontology" partition)))
           (entity (%cg-detach view))
           (fact (%cg-object "fact_id" "fact:original" "subject_id" "entity:operator" "object_id" "node:cat:v1"
                             "fact" "The operator owns Mina." "evidence" #("The original name was Mina.")))
           (delta (gethash "value" (context-graph-plan-entity-revision context grant view))))
      (remhash "observed_at" entity) (remhash "application_id" entity)
      (setf (gethash "entity:cat" (context-graph-entities graph)) (%cg-detach entity)
            (gethash "node:cat:v1" (context-graph-entity-versions graph)) entity
            (gethash "entity:cat" (context-graph-current-entity-versions graph)) "node:cat:v1"
            (gethash "fact:original" (context-graph-facts graph)) fact)
      (let* ((before (%cg-authority-canonical-json (vector (context-graph-entities graph) (context-graph-entity-versions graph)
                                                         (context-graph-current-entity-versions graph) (context-graph-facts graph))))
             (staged (%cg-stage-authority-state graph))
             (new-id (gethash "node_id" (gethash "create_version" delta))))
        (%cg-install-revision-delta staged delta)
        (ag-check "mechanical installation leaves original projection unchanged"
                  (equal before (%cg-authority-canonical-json (vector (context-graph-entities graph) (context-graph-entity-versions graph)
                                                                     (context-graph-current-entity-versions graph) (context-graph-facts graph)))))
        (ag-check "current cache has corrected primary label" (equal "Mira" (gethash "label" (gethash "entity:cat" (context-graph-entities staged)))))
        (ag-check "old descriptor retained as superseded" (equal "superseded" (gethash "status" (gethash "node:cat:v1" (context-graph-entity-versions staged)))))
        (ag-check "replacement uses shared deterministic node ID" (gethash new-id (context-graph-entity-versions staged)))
        (ag-check "incident evidence and version endpoints are untouched" (%cg-authority-equal-p (context-graph-facts graph) (context-graph-facts staged)))
        (ag-check "version count differs from enduring identity count" (and (= 2 (hash-table-count (context-graph-entity-versions staged)))
                                                                            (= 1 (context-graph-entity-count staged))))
        (ag-check "complete delta retained as lineage evidence" (= 1 (hash-table-count (context-graph-revision-lineage staged))))
        (%cg-install-staged-state graph staged)
        (ag-check "state publication includes all new indexes" (equal new-id (gethash "entity:cat" (context-graph-current-entity-versions graph))))
        (setf (gethash "quote" (gethash "evidence" delta)) "Changed")
        (ag-check "installer does not retain caller-owned delta objects"
                  (not (equal "Changed" (gethash "quote" (gethash "evidence" (gethash (gethash "operation_id" delta) (context-graph-revision-lineage graph)))))))))))
(format t "AUTHORITY-INSTALLATION ~d passed, 0 failed~%" *authority-installation-checks*)
