;;;; harness: bare
(load (merge-pathnames "context-graph-simple-model-tests.lisp" *load-truename*))
(in-package :pai.context-graph)
(let* ((ontology (gethash "ontology" (as-fixture)))
       (graph (make-context-graph ontology))
       (revision "personal-context-core-glm53-v1.2")
       (episode (sm-episode "runtime-first" "I own a cat named Mina." 100))
       (simple (sm-proposal)) (phases nil))
  (multiple-value-bind (context boundary) (lab-authority-context graph episode 0)
    (let* ((before (%cg-authority-projection-digest graph "lab-agent" "lab-persona"))
           (result (context-graph-generate-reviewed context ontology revision
                     (lambda (phase spec digest)
                       (declare (ignore spec))
                       (assert (= 64 (length digest)))
                       (push phase phases)
                       (cond ((equal phase "entities") (%cg-object "new_entities" (gethash "new_entities" simple)))
                             ((equal phase "facts") (%cg-object "facts" (gethash "facts" simple) "name_corrections" #()))
                             ((equal phase "review") (sm-review context (%cgs-expand context ontology revision simple)))
                             (t (error "Unexpected phase"))))))
           (envelope (gethash "value" result)))
      (assert (equal '("entities" "facts" "review") (reverse phases)))
      (assert (equal before (%cg-authority-projection-digest graph "lab-agent" "lab-persona")))
      (assert (equal "accepted" (gethash "status" (context-graph-apply-reviewed-generation graph boundary envelope))))
      (assert (= 1 (length (gethash "facts" (gethash "context" (%cg-authority-retrieve graph "lab-agent" "lab-persona" "Mina"))))))
      (let ((bad (%cg-detach envelope)))
        (setf (gethash "response_digest" (gethash "review_binding" bad)) (%cg-sha256 "changed"))
        (assert (sm-error (lambda () (context-graph-apply-reviewed-generation graph boundary bad)) "MODEL_REVIEW_INVALID"))))
    (let ((calls 0))
      (assert (eq :paused-budget
                  (context-graph-generate-reviewed context ontology revision
                    (lambda (&rest args) (declare (ignore args)) (incf calls) :paused-budget))))
      (assert (= 1 calls)))))
(format t "RUNTIME-GENERATION orchestration, read-only generation, admission, retrieval, tamper and budget checks passed~%")
