;;;; harness: bare
(load (merge-pathnames "context-graph-simple-model-tests.lisp" *load-truename*))
(in-package :pai.context-graph)
(defvar *retrieval-checks* 0)
(defun rt-check (name value)
  (unless value (error "FAIL ~a" name)) (incf *retrieval-checks*) (format t "PASS ~a~%" name))
(defun rt-rows (result channel &optional (surface "context")) (gethash channel (gethash surface result)))
(defun rt-label (row) (gethash "label" (gethash "descriptor" (gethash "value" row))))
(defun rt-fixture ()
  (multiple-value-bind (partition unused participants) (as-fixture)
    (declare (ignore unused participants))
    (let* ((ontology (gethash "ontology" partition)) (revision "personal-context-core-glm53-v1.2")
           (text "Mina is a playful cat. I have B12 deficiency. Star Atlas, also called Skybook, is an astronomy guide.")
           (episode (sm-episode "retrieval-one" text 100))
           (simple (%cg-object "new_entities"
                     (vector (%cg-object "name" "Mina" "kind" "organism" "alternate_names" #() "categories" #("cat"))
                             (%cg-object "name" "B12 deficiency" "kind" "condition" "alternate_names" #() "categories" #("deficiency"))
                             (%cg-object "name" "Star Atlas" "kind" "artifact" "alternate_names" #("Skybook") "categories" #("astronomy")))
                     "facts" (vector (%cg-object "subject" "operator" "predicate" "has_condition" "object" "new_2"
                                   "statement" "The operator reports having B12 deficiency." "scope" "assertion" "polarity" "positive" "attributed_to" "operator"
                                   "time" (%cg-object "character" "ongoing-state" "occurred_at" :null "valid_from" :null "valid_until" :null)
                                   "evidence" (vector (%cg-object "source" "source_1" "quote" "I have B12 deficiency.")))) "name_corrections" #()))
           (step (%cg-object "episode" episode "proposal" simple "review" :null "request_digest" :null)))
      (setf (gethash "entity_types" ontology) #("person" "agent" "organism" "condition" "artifact")
            (gethash "edge_types" ontology) (concatenate 'vector (gethash "edge_types" ontology)
                    (vector (%cg-object "name" "has_condition" "subject_types" #("person") "object_types" #("condition")))))
      (let ((graph (make-context-graph ontology))
            (lexicon (context-graph-retrieval-lexicon
                      (%cg-object "entity_types" (vector (%cg-object "name" "condition" "definition" "A medical or health-related state or deficiency."
                                                                      "exclusion_rule" "Volcanic apparatus."))
                                  "predicates" (vector (%cg-object "name" "has_condition" "definition" "Subject has a medical condition."))))))
        (multiple-value-bind (context boundary) (lab-authority-context graph episode 0)
          (declare (ignore boundary))
          (setf (gethash "request_digest" step) (gethash "request_digest" (lab-authority-step graph step 0 revision t))
                (gethash "review" step) (sm-review context (%cgs-expand context ontology revision simple)))
          (lab-authority-step graph step 0 revision t)
          (values graph (gethash "source_packet" context) lexicon
                  (%cg-object "schema_version" 2 "authority_operation" "retrieval-session" "source_kind" "synthetic-controlled"
                              "ontology" ontology "ontology_revision" revision "history" (vector step)
                              "retrieval_lexicon" lexicon "queries" #("CAT mina" "health issue" "SKYBOOK" "volcanic apparatus"))))))))
(multiple-value-bind (graph packet lexicon bundle) (rt-fixture)
  (let ((before (%cg-authority-projection-digest graph "lab-agent" "lab-persona")))
    (labels ((ask (query &rest options) (apply #'%cg-authority-retrieve graph "lab-agent" "lab-persona" query
                                              :source-packet packet :lexicon lexicon options)))
      (let* ((result (ask "CAT mina")) (entities (rt-rows result "entities")))
        (rt-check "isolated entity retrieved by separated case-insensitive terms" (equal "Mina" (rt-label (aref entities 0))))
        (rt-check "isolated entity does not invent a fact" (zerop (length (rt-rows result "facts"))))
        (rt-check "entity term coverage recorded" (= 2 (length (gethash "matched_terms" (aref entities 0)))))
        (rt-check "context bounded and explicitly measured" (and (<= (gethash "context_bytes" result) 6000)
                                                               (= (%cgr-bytes (gethash "context" result)) (gethash "context_bytes" result)))))
      (let ((value (gethash "value" (aref (rt-rows (ask "B12") "facts") 0))))
        (rt-check "answer-bearing statement survives retrieval"
                  (equal "The operator reports having B12 deficiency." (gethash "statement" value)))
        (rt-check "exact admitted quote survives with source coordinates"
                  (let* ((excerpt (aref (gethash "evidence_excerpts" value) 0))
                         (original (aref (gethash "sources" packet) 0)))
                    (and (equal "I have B12 deficiency." (gethash "quote" excerpt))
                         (equal (gethash "quote" excerpt)
                                (subseq (gethash "text" original) (gethash "start_char" excerpt) (gethash "end_char" excerpt)))))))
      (rt-check "statement-only vocabulary discovers stored claim"
                (= 1 (length (rt-rows (ask "reports") "facts"))))
      (let* ((first (aref (rt-rows (ask "B12") "facts") 0))
             (second (%cg-detach first)))
        ;; Presentation-only fixture: no admission or graph mutation.
        (setf (gethash "statement" (gethash "value" second)) "A distinct value-bearing statement.")
        (rt-check "same endpoints do not erase distinct statements"
                  (= 2 (length (gethash "facts" (%cgr-select #() (vector first second) #() 16000 #(0 4 0)))))))
      (rt-check "alias hit" (equal "Star Atlas" (rt-label (aref (rt-rows (ask "skyBOOK") "entities") 0))))
      (rt-check "category hit" (equal "Star Atlas" (rt-label (aref (rt-rows (ask "astronomy") "entities") 0))))
      (let ((result (ask "health issue")))
        (rt-check "general ontology meaning reaches condition" (equal "B12 deficiency" (rt-label (aref (rt-rows result "entities") 0))))
        (rt-check "general meaning retrieves useful grounded fact" (equal "has_condition" (gethash "predicate" (gethash "value" (aref (rt-rows result "facts") 0))))))
      (dolist (q '("volcanic apparatus" "minaret" "the and what about"))
        (rt-check (format nil "negative ~a" q) (every (lambda (key) (zerop (length (rt-rows (ask q) key)))) '("entities" "facts" "sources"))))
      (let* ((result (ask "playful")) (source (gethash "value" (aref (rt-rows result "sources") 0)))
             (original (aref (gethash "sources" packet) 0)))
        (rt-check "source-only term discovers nearby current name" (equal "Mina" (rt-label (aref (rt-rows result "entities") 0))))
        (rt-check "source excerpt retains exact coordinates" (equal (gethash "text" source)
                 (subseq (gethash "text" original) (gethash "start_char" source) (gethash "end_char" source))))
        (rt-check "source excerpt not presented as fact" (and (zerop (length (rt-rows result "facts")))
                     (equal "source-text-not-an-admitted-fact" (gethash "interpretation" source)))))
      (rt-check "keyword repetition does not increase score"
                (= (gethash "score" (aref (rt-rows (ask "Mina") "entities") 0))
                   (gethash "score" (aref (rt-rows (ask "Mina Mina Mina") "entities") 0))))
      (rt-check "small byte budget excludes oversize rows" (and (<= (gethash "context_bytes" (ask "health cat astronomy" :maximum-bytes 128)) 128)
                                (plusp (gethash "selection_skipped" (ask "health cat astronomy" :maximum-bytes 128)))))
      (rt-check "scan incompleteness explicit" (eq :false (gethash "scan_complete" (ask "Mina" :scan-limit 1))))
      (rt-check "candidate truncation explicit" (eq :true (gethash "candidates_truncated" (ask "health cat astronomy" :candidate-limit 1))))
      (rt-check "repeat deterministic" (equal (%cg-authority-canonical-json (ask "health cat")) (%cg-authority-canonical-json (ask "health cat")))))
    (let* ((results (gethash "queries" (gethash "value" (al-run bundle)))))
      (rt-check "actual lab subprocess returns isolated entity" (equal "Mina" (rt-label (aref (rt-rows (aref results 0) "entities") 0))))
      (rt-check "actual lab subprocess returns health fact" (= 1 (length (rt-rows (aref results 1) "facts")))))
    (rt-check "retrieval performs zero graph writes" (equal before (%cg-authority-projection-digest graph "lab-agent" "lab-persona"))))
  (let* ((entity (find "condition" (loop for e being the hash-values of (context-graph-entities graph) collect e)
                       :test #'equal :key (lambda (e) (gethash "kind" e))))
         (receipt (%cg-object "query_sha256" (%cg-sha256 "wellbeing")
                              "projection_watermark" (%cg-authority-watermark graph "lab-agent" "lab-persona")
                              "source_packet_digest" (%cg-authority-digest "retrieval-sources" packet) "encoder_revision" "synthetic-encoder-v1"
                              "hits" (vector (%cg-object "kind" "entity" "id" (gethash "entity_id" entity) "score_milli" 900)))))
    (labels ((ask () (%cg-authority-retrieve graph "lab-agent" "lab-persona" "wellbeing" :source-packet packet :lexicon lexicon :semantic-receipt receipt)))
      (rt-check "strong semantic vocabulary-gap entity" (equal "B12 deficiency" (rt-label (aref (rt-rows (ask) "entities") 0))))
      (rt-check "semantic endpoint finds grounded fact without promoting text" (= 1 (length (rt-rows (ask) "facts"))))
      (setf (gethash "score_milli" (aref (gethash "hits" receipt) 0)) 200)
      (rt-check "weak semantic-only hit excluded" (zerop (length (rt-rows (ask) "entities"))))
      (setf (gethash "id" (aref (gethash "hits" receipt) 0)) "foreign:entity")
      (rt-check "foreign semantic ID never fetches outside partition" (= 1 (gethash "ignored_semantic_hits" (ask))))
      (setf (gethash "query_sha256" receipt) (%cg-sha256 "other query"))
      (rt-check "stale semantic query binding rejected" (sm-error #'ask "RETRIEVAL_SEMANTIC_BINDING_INVALID")))))
(multiple-value-bind (graph packet lexicon bundle) (rt-fixture)
  (declare (ignore bundle))
  (let* ((result (%cg-authority-retrieve graph "lab-agent" "lab-persona" "Mina" :source-packet packet :lexicon lexicon))
         (fact (loop for f being the hash-values of (context-graph-facts graph) return f)))
    (rt-check "direct match excludes proximity-only context distractors" (= 1 (length (rt-rows result "entities"))))
    (rt-check "broader discovery remains separately inspectable" (> (length (rt-rows result "entities" "candidates")) 1))
    (dolist (pair '(("scope" . "hypothesis") ("polarity" . "negative") ("source_basis" . "reported")))
      (let* ((grounding (gethash "grounding" fact)) (old (gethash (car pair) grounding)))
        (unwind-protect
             (progn (setf (gethash (car pair) grounding) (cdr pair))
                    (rt-check (format nil "nonfactual ~a excluded" (cdr pair))
                              (zerop (length (rt-rows (%cg-authority-retrieve graph "lab-agent" "lab-persona" "health" :lexicon lexicon) "facts")))))
          (setf (gethash (car pair) grounding) old))))
    (setf (gethash "text_sha256" (aref (gethash "sources" packet) 0)) (%cg-sha256 "forged"))
    (rt-check "source hash drift refused" (sm-error (lambda () (%cg-authority-retrieve graph "lab-agent" "lab-persona" "Mina" :source-packet packet)) "RETRIEVAL_SOURCE_INVALID"))))
(rt-check "window start cannot create a suffix match" (not (%cgr-term-in-range-p "cat" "bobcat" 3 6)))
(rt-check "window end cannot create a prefix match" (not (%cgr-term-in-range-p "cat" "catalog" 0 3)))
(rt-check "UTF8 budget measures bytes not characters" (> (%cgr-bytes (%cg-object "text" (string (code-char 233))))
                                                       (length (%cg-authority-canonical-json (%cg-object "text" (string (code-char 233)))))))
(format t "RETRIEVAL ~d passed, 0 failed~%" *retrieval-checks*)
