;;;; harness: bare
(require :asdf)
(unless (find-package :ql) (load (or (uiop:getenv "PAI_QUICKLISP_SETUP") "/opt/quicklisp/setup.lisp")))
(asdf:load-asd (merge-pathnames "../pai-context-graph.asd" *load-truename*))
(asdf:load-system :pai-context-graph)
(in-package :pai.context-graph)
(load (merge-pathnames "fixtures/context-graph-authority-fixtures.lisp" *load-truename*))
(load (merge-pathnames "fixtures/context-graph-authority-lab-driver.lisp" *load-truename*))
(load (merge-pathnames "../scripts/context-graph-authority-session.lisp" *load-truename*))
(defvar *simple-checks* 0)
(defun sm-check (name value) (unless value (error "FAIL ~a" name)) (incf *simple-checks*) (format t "PASS ~a~%" name))
(defun sm-error (thunk code)
  (handler-case (progn (funcall thunk) nil)
    (context-graph-authority-input-error (error) (equal code (%cg-authority-error-code error)))))
(defun sm-episode (id text time)
  (%cg-object "case_id" id "timestamp" time "sources"
              (vector (%cg-object "source_id" id "speaker_id" "operator" "kind" "original-utterance" "text" text))))
(defun sm-proposal ()
  (%cg-object "new_entities" (vector (%cg-object "name" "Mina" "kind" "organism" "alternate_names" #() "categories" #("cat")))
              "facts" (vector (%cg-object "subject" "operator" "object" "new_1" "predicate" "owns" "statement" "The operator owns a cat."
                                          "scope" "assertion" "polarity" "positive" "attributed_to" "operator"
                                          "time" (%cg-object "character" "ongoing-state" "occurred_at" :null "valid_from" :null "valid_until" :null)
                                          "evidence" (vector (%cg-object "source" "source_1" "quote" "I own a cat named Mina."))))
              "name_corrections" #()))
(defun sm-review (context raw)
  (let ((prepared (gethash "proposal" (gethash "value" (%cgm-prepare context raw (gethash "ontology_revision" raw))))))
    (%cg-object "schema_version" 2
                "claim_reviews" (map 'vector (lambda (claim) (%cg-object "claim_ref" (gethash "claim_ref" claim)
                                                "verdict" "DIRECTLY_EVIDENCED" "evidence" "Exact synthetic source supports this descriptor or fact.")) (%cgm-claims prepared))
                "revision_reviews" (if (plusp (length (gethash "entity_revisions" prepared))) (gethash "reviews" (at-raw-review context prepared)) #()))))
(multiple-value-bind (partition unused participants) (as-fixture)
  (declare (ignore unused participants))
  (let* ((ontology (gethash "ontology" partition)) (revision "personal-context-core-glm53-v1.2")
         (graph (make-context-graph ontology)) (simple (sm-proposal))
         (episode (sm-episode "first" "I own a cat named Mina." 100))
         (step (%cg-object "episode" episode "proposal" simple "review" :null "request_digest" :null))
         (bundle (%cg-object "schema_version" 2 "authority_operation" "simple-model-session" "source_kind" "synthetic-controlled"
                             "ontology" ontology "ontology_revision" revision "history" #() "step" step "queries" #("Mina" "cat" "tea"))))
    (multiple-value-bind (context boundary) (lab-authority-context graph episode 0)
      (declare (ignore boundary))
      (let* ((before (%cg-authority-canonical-json simple)) (raw (%cgs-expand context ontology revision simple))
             (spec (%cgs-extraction-input context ontology revision))
             (text (%cg-authority-canonical-json (gethash "value" spec))))
        (sm-check "translation leaves simple input unchanged" (equal before (%cg-authority-canonical-json simple)))
        (sm-check "runtime supplies versions and provenance status"
                  (and (= 4 (gethash "schema_version" raw)) (equal "unreviewed" (gethash "evidence_status" (aref (gethash "entities" raw) 0)))) )
        (sm-check "source handle resolves to exact original source ID"
                  (equal "first" (gethash "source_id" (aref (gethash "evidence" (gethash "grounding" (aref (gethash "relationships" raw) 0))) 0))))
        (sm-check "model input omits internal digests and node IDs"
                  (and (not (search "revision_digest" text)) (not (search "node_id" text)) (not (search "local_ref" text))))
        (sm-check "categories remain distinct from aliases"
                  (let ((entity (aref (gethash "entities" raw) 0)))
                    (and (equalp #("cat") (gethash "classifications" entity)) (zerop (length (gethash "aliases" entity))))))
        (let ((bad (%cg-detach simple)))
          (setf (gethash "schema_version" bad) 4)
          (sm-check "extra authority fields are rejected" (sm-error (lambda () (%cgs-expand context ontology revision bad)) "SIMPLE_PROPOSAL_INVALID")))
        (let ((bad (%cg-detach simple)))
          (setf (gethash "object" (aref (gethash "facts" bad) 0)) "new_2")
          (sm-check "nonexistent new handle rejected" (sm-error (lambda () (%cgs-expand context ontology revision bad)) "SIMPLE_HANDLE_INVALID")))
        (let ((bad (%cg-detach simple)))
          (setf (gethash "source" (aref (gethash "evidence" (aref (gethash "facts" bad) 0)) 0)) "source_2")
          (sm-check "unknown source rejected" (sm-error (lambda () (%cgs-expand context ontology revision bad)) "SIMPLE_PROPOSAL_INVALID")))
        (let ((negative (%cg-detach simple)))
          (setf (gethash "polarity" (aref (gethash "facts" negative) 0)) "negative"
                (gethash "scope" (aref (gethash "facts" negative) 0)) "hypothesis")
          (let ((expanded (%cgs-expand context ontology revision negative)))
            (sm-check "translator does not upgrade scope or polarity"
                      (let ((grounding (gethash "grounding" (aref (gethash "relationships" expanded) 0))))
                        (and (equal "negative" (gethash "polarity" grounding)) (equal "hypothesis" (gethash "scope" grounding)))))))
        (let ((bad (%cg-detach simple)))
          (setf (gethash "object" (aref (gethash "facts" bad) 0)) "operator")
          (sm-check "valid simple syntax cannot bypass ontology endpoint validation"
                    (sm-error (lambda () (%cgm-validate-ontology context (%cgs-expand context ontology revision bad) ontology revision))
                              "RELATIONSHIP_KIND_INVALID")))
        (let ((review-spec (lab-authority-step graph step 0 revision t)))
          (setf (gethash "review" step) (sm-review context raw) (gethash "request_digest" step) (gethash "request_digest" review-spec)))
        (sm-check "reviewed simple episode applies through actual subprocess"
                  (equal "accepted" (gethash "status" (al-run bundle))))
        (sm-check "direct simple application matches qualified pipeline"
                  (equal "accepted" (gethash "status" (lab-authority-step graph step 0 revision t))))))
    (let* ((episode2 (sm-episode "second" "The stored name of my cat is wrong. Her name is Mira, not Mina." 200))
           (correction (%cg-object "new_entities" #() "facts" #() "name_corrections"
                                  (vector (%cg-object "target" "known_1" "corrected_name" "Mira" "interpretation" "error-correction"
                                                     "evidence" (%cg-object "source" "source_1" "quote" "The stored name of my cat is wrong. Her name is Mira, not Mina.")))))
           (next (%cg-object "episode" episode2 "proposal" correction "review" :null "request_digest" :null)))
      (multiple-value-bind (context boundary) (lab-authority-context graph episode2 1)
        (declare (ignore boundary))
        (let* ((before (%cg-authority-canonical-json context)) (raw (%cgs-expand context ontology revision correction))
               (entity (aref (gethash "entities" raw) 0)) (change (aref (gethash "entity_revisions" raw) 0))
               (prior (aref (gethash "eligible_entities" context) 0)))
          (sm-check "one correction mechanically joins entity and revision" (equal (gethash "local_ref" entity) (gethash "local_ref" change)))
          (sm-check "runtime binds target and revision digest"
                    (and (equal (gethash "entity_id" prior) (gethash "target_entity_id" change))
                         (equal (gethash "revision_digest" prior) (gethash "expected_revision_digest" change))))
          (sm-check "correction preserves immutable classifications" (equalp (gethash "classifications" entity) #("cat")))
          (sm-check "translation leaves context unchanged" (equal before (%cg-authority-canonical-json context)))
          (let* ((review (sm-review context raw))
                 (candidate (aref (gethash "candidate_assessments" (aref (gethash "revision_reviews" review) 0)) 0))
                 (unanchored (%cg-detach next)) (isolated (%cg-detach bundle)))
            (setf (gethash "request_digest" unanchored) (gethash "request_digest" (lab-authority-step graph unanchored 1 revision t))
                  (gethash "anchor_fact_ids" candidate) #()
                  (gethash "review" unanchored) review
                  (gethash "history" isolated) (vector step) (gethash "step" isolated) unanchored)
            (let* ((result (al-run isolated))
                   (application (gethash "application" (gethash "value" result))))
              (sm-check "accepted envelope with unanchored review still defers correction"
                        (and (equal "accepted" (gethash "status" result))
                             (equal "deferred" (gethash "formation_outcome" application))))))
          (let ((bad (%cg-detach correction)))
            (setf (gethash "name_corrections" bad) (vector (aref (gethash "name_corrections" correction) 0) (aref (gethash "name_corrections" correction) 0)))
            (sm-check "duplicate target rejected" (sm-error (lambda () (%cgs-expand context ontology revision bad)) "SIMPLE_CORRECTION_TARGET_INVALID")))
          (let ((ambiguous (%cg-detach context)))
            (setf (gethash "correction_scopes" ambiguous) (concatenate 'vector (gethash "correction_scopes" context) (gethash "correction_scopes" context)))
            (sm-check "multiple correction scopes fail closed" (handler-case (progn (%cgs-expand ambiguous ontology revision correction) nil)
                                                                (context-graph-authority-input-error () t))))
          (let ((review-spec (lab-authority-step graph next 1 revision t)))
            (setf (gethash "review" next) (sm-review context raw) (gethash "request_digest" next) (gethash "request_digest" review-spec)))
          (setf (gethash "history" bundle) (vector step) (gethash "step" bundle) next (gethash "queries" bundle) #("Mira" "cat" "Mina" "tea"))
          (let* ((result (al-run bundle)) (queries (gethash "queries" result)))
            (sm-check "actual lab correction retrieves current name and explicit type"
                      (and (equal "accepted" (gethash "status" result)) (= 1 (length (gethash "rows" (aref queries 0))))
                           (= 1 (length (gethash "rows" (aref queries 1))))))
            (sm-check "corrected result preserves enduring target"
                      (equal (gethash "entity_id" prior) (gethash "entity_id" (gethash "object" (aref (gethash "rows" (aref queries 0)) 0)))))
            (sm-check "old name and unrelated term are excluded"
                      (and (zerop (length (gethash "rows" (aref queries 2)))) (zerop (length (gethash "rows" (aref queries 3))))))))))))
(format t "SIMPLE-MODEL ~d passed, 0 failed~%" *simple-checks*)
