;;;; harness: bare
(require :asdf)
(unless (find-package :ql)
  (load (or (uiop:getenv "PAI_QUICKLISP_SETUP") "/opt/quicklisp/setup.lisp")))
(asdf:load-asd (merge-pathnames "../pai-context-graph.asd" *load-truename*))
(asdf:load-system :pai-context-graph)
(in-package :pai.context-graph)
(defvar *authority-revision-checks* 0)
(defun ar-check (name value)
  (unless value (error "FAIL ~a" name))
  (incf *authority-revision-checks*) (format t "PASS ~a~%" name))
(load (merge-pathnames "fixtures/context-graph-authority-fixtures.lisp" *load-truename*))
(defun ar-error-p (context grant view)
  (handler-case (progn (context-graph-plan-entity-revision context grant view) nil)
    (context-graph-authority-input-error () t)))
(multiple-value-bind (context grant view) (ar-fixture)
  (let* ((before (%cg-authority-canonical-json (vector context grant view)))
         (result (context-graph-plan-entity-revision context grant view))
         (delta (gethash "value" result)) (new (gethash "create_version" delta)))
    (ar-check "admitted grant produces a mechanical delta" (equal "accepted" (gethash "status" result)))
    (ar-check "enduring identity retained" (equal "entity:cat" (gethash "entity_id" new)))
    (ar-check "descriptor version changes" (not (equal "node:cat:v1" (gethash "node_id" new))))
    (ar-check "prior version closed not deleted" (equal "superseded" (gethash "status" (gethash "close_version" delta))))
    (ar-check "current alias policy removes only old and new primary spellings"
              (equalp #("Pet" "Little cat") (gethash "aliases" new)))
    (ar-check "classification preserved" (equalp #("cat") (gethash "classifications" new)))
    (ar-check "facts absent from descriptor-only delta" (not (gethash "facts" delta)))
    (ar-check "history lineage retained" (equal "node:cat:v1" (gethash "old_node_id" (gethash "lineage" delta))))
    (ar-check "current index uses new version" (equal (gethash "node_id" new) (gethash "node_id" (gethash "current_version" delta))))
    (ar-check "planning is byte deterministic"
              (equal (%cg-authority-canonical-json result)
                     (%cg-authority-canonical-json (context-graph-plan-entity-revision context grant view))))
    (ar-check "caller-owned inputs unchanged" (equal before (%cg-authority-canonical-json (vector context grant view))))
    (setf (aref (gethash "classifications" new) 0) "changed")
    (setf (gethash "quote" (gethash "evidence" delta)) "changed")
    (ar-check "all delta descendants detached" (equal before (%cg-authority-canonical-json (vector context grant view))))))
(multiple-value-bind (context grant view) (ar-fixture)
  (setf (gethash "node_id" view) "node:cat:v2" (gethash "revision_digest" view) (%cg-revision-descriptor-digest view))
  (ar-check "changed current version is stale" (equal "incomplete" (gethash "status" (context-graph-plan-entity-revision context grant view)))))
(dolist (change '("grant-digest" "view-digest" "source-span" "partition" "participant" "unknown-key"))
  (multiple-value-bind (context grant view) (ar-fixture)
    (cond ((equal change "grant-digest") (setf (gethash "grant_id" grant) (%cg-sha256 "forged")))
          ((equal change "view-digest") (setf (gethash "label" view) "Tampered"))
          ((equal change "source-span") (setf (gethash "start_char" (gethash "evidence" grant)) 1
                                               (gethash "grant_id" grant) (%cg-revision-grant-id grant)))
          ((equal change "partition") (setf (gethash "persona_id" context) "persona:foreign"))
          ((equal change "participant") (setf (gethash "participant_role" view) "operator"
                                               (gethash "revision_digest" view) (%cg-revision-descriptor-digest view)))
          ((equal change "unknown-key") (setf (gethash "confidence" grant) 100)))
    (ar-check change (ar-error-p context grant view))))
(multiple-value-bind (context grant view) (ar-fixture "Mina" "The name is Mina.")
  (ar-check "noop cannot create a version" (ar-error-p context grant view)))
(multiple-value-bind (context grant view) (ar-fixture "MINA" "The spelling is MINA.")
  (ar-check "case-only correction creates a version" (equal "accepted" (gethash "status" (context-graph-plan-entity-revision context grant view)))))
(multiple-value-bind (context grant view) (ar-fixture "Unstated" "The spelling is Mira.")
  (ar-check "conversational replacement must be literal" (ar-error-p context grant view)))
(format t "AUTHORITY-REVISION ~d passed, 0 failed~%" *authority-revision-checks*)
