;;;; harness: bare
(require :asdf)
(unless (find-package :ql) (load (or (uiop:getenv "PAI_QUICKLISP_SETUP") "/opt/quicklisp/setup.lisp")))
(asdf:load-asd (merge-pathnames "../pai-context-graph.asd" *load-truename*))
(asdf:load-system :pai-context-graph)
(in-package :pai.context-graph)
(load (merge-pathnames "fixtures/context-graph-authority-fixtures.lisp" *load-truename*))
(load (merge-pathnames "fixtures/context-graph-authority-lab-driver.lisp" *load-truename*))
(load (merge-pathnames "../scripts/context-graph-authority-session.lisp" *load-truename*))
(defvar *model-adapter-checks* 0)
(defun am-check (name value)
  (unless value (error "FAIL ~a" name)) (incf *model-adapter-checks*) (format t "PASS ~a~%" name))
(defun am-error (fn)
  (handler-case (progn (funcall fn) nil) (context-graph-authority-input-error () t)))
(defun am-episode (id text time)
  (%cg-object "case_id" (substitute #\- #\: id) "timestamp" time "sources"
              (vector (%cg-object "source_id" id "speaker_id" "operator" "kind" "original-utterance" "text" text))))
(defun am-proposal ()
  (%cg-object "schema_version" 4 "ontology_revision" "personal-context-core-glm53-v1.2"
              "entities" (vector (%cg-object "local_ref" "cat" "kind" "organism" "label" "Mina" "aliases" #()
                                             "classifications" #("cat") "identity_action" "NEW" "existing_node_id" :null
                                             "evidence_status" "unreviewed" "evidence_note" "pending independent review"))
              "relationships" (vector (%cg-object "subject_ref" "runtime:operator" "predicate" "owns" "object_ref" "cat"
                                                  "relationship_action" "ASSERT" "fact" "The operator owns a cat named Mina."
                                                  "grounding" (%cg-object "schema_version" 2 "scope" "assertion" "polarity" "positive"
                                                                          "attributed_to_ref" "runtime:operator"
                                                                          "evidence" (vector (%cg-object "source_id" "episode:first" "quote" "I own a cat named Mina.")))
                                                  "temporal" (%cg-object "schema_version" 1 "character" "standing-disposition"
                                                                         "occurred_at" :null "valid_from" :null "valid_until" :null)
                                                  "evidence_status" "unreviewed" "evidence_note" "pending independent review"))
              "entity_revisions" #()))
(defun am-review (context raw)
  (let ((prepared (gethash "proposal" (gethash "value" (%cgm-prepare context raw (gethash "ontology_revision" raw))))))
    (%cg-object "schema_version" 2
                "claim_reviews" (map 'vector (lambda (claim) (%cg-object "claim_ref" (gethash "claim_ref" claim)
                                                                         "verdict" "DIRECTLY_EVIDENCED" "evidence" "Synthetic independent review of exact source.")) (%cgm-claims prepared))
                "revision_reviews" (if (plusp (length (gethash "entity_revisions" prepared))) (gethash "reviews" (at-raw-review context prepared)) #()))))
(defun am-response (name payload)
  (%cg-object "choices" (vector (%cg-object "finish_reason" "tool_calls" "message"
                                            (%cg-object "tool_calls" (vector (%cg-object "function" (%cg-object "name" name "arguments" (%cg-authority-canonical-json payload)))))))))
(defun am-save-cli-replay (first-step second-step)
  ;; Disposable artifacts used by the CLI integration check, never source data.
  (flet ((save (name value)
           (with-open-file (stream (merge-pathnames name (uiop:temporary-directory)) :direction :output :if-exists :supersede :external-format :utf-8)
             (write-string (%cg-authority-canonical-json value) stream))))
    (save "pai-authority-model-recorded-responses.json"
          (%cg-object "episode-01-extraction" (am-response "write-knowledge-graph-formation" (gethash "proposal" first-step))
                      "episode-01-review" (am-response "review-knowledge-graph-evidence" (gethash "review" first-step))
                      "episode-02-extraction" (am-response "write-knowledge-graph-formation" (gethash "proposal" second-step))
                      "episode-02-review" (am-response "review-knowledge-graph-evidence" (gethash "review" second-step))))
    (save "pai-authority-model-recorded-corpus.json"
          (%cg-object "source_kind" "synthetic-controlled" "cases" (vector (gethash "episode" first-step) (gethash "episode" second-step))
                      "queries" (vector (%cg-object "query" "Mira" "expected_count" 1 "expected_object_label" "Mira")
                                        (%cg-object "query" "cat" "expected_count" 1 "expected_object_label" "Mira")
                                        (%cg-object "query" "Mina" "expected_count" 0 "expected_object_label" :null)
                                        (%cg-object "query" "tea" "expected_count" 0 "expected_object_label" :null))))))
(multiple-value-bind (partition ignored participants) (as-fixture)
  (declare (ignore ignored participants))
  (let* ((graph (make-context-graph (gethash "ontology" partition))) (raw (am-proposal))
         (episode (am-episode "episode:first" "I own a cat named Mina." 100))
         (step (%cg-object "episode" episode "proposal" :null "review" :null "request_digest" :null))
         (bundle (%cg-object "schema_version" 2 "authority_operation" "model-session" "source_kind" "synthetic-controlled"
                             "ontology" (gethash "ontology" partition) "ontology_revision" (gethash "ontology_revision" raw)
                             "history" #() "step" step "queries" #("Mina" "cat" "tea"))))
    (let ((extraction (al-run bundle)))
      (am-check "lab builds model schema before any proposal exists" (equal "write-knowledge-graph-formation" (gethash "tool_name" (gethash "value" extraction)))))
    (multiple-value-bind (context boundary) (lab-authority-context graph episode 0)
      (declare (ignore boundary))
      (let ((forged (%cg-detach raw)))
        (setf (gethash "evidence_status" (aref (gethash "entities" forged) 0)) "direct")
        (am-check "extractor cannot supply its own reviewed authority"
                  (am-error (lambda () (%cgm-prepare context forged (gethash "ontology_revision" raw))))))
      (let ((elided (%cg-detach raw)))
        (setf (gethash "quote" (aref (gethash "evidence" (gethash "grounding" (aref (gethash "relationships" elided) 0))) 0)) "I own ... named Mina.")
        (let* ((spec (%cgm-review-input context elided (gethash "ontology_revision" raw)))
               (claims (gethash "claims" (gethash "input" (gethash "value" spec)))))
          (am-check "independent reviewer receives the whole recovered quote"
                    (equal "I own a cat named Mina." (gethash "quote" (aref (gethash "evidence" (gethash "grounding" (gethash "claim" (aref claims 1)))) 0))))))
      (setf (gethash "proposal" step) raw)
      (let ((invalid (%cg-detach step)))
        (setf (gethash "kind" (aref (gethash "entities" (gethash "proposal" invalid)) 0)) "person")
        (am-check "ontology-invalid endpoint fails before review request construction"
                  (am-error (lambda () (lab-authority-step graph invalid 0 (gethash "ontology_revision" raw))))))
      (let* ((review-input (al-run bundle)) (review (am-review context raw))
             (claims (gethash "claims" (gethash "input" (gethash "value" review-input)))))
        (am-check "runtime participants excluded from ordinary model claims" (= 2 (length claims)))
        (am-check "review sees runtime-prepared exact offsets" (= 0 (gethash "start_char" (aref (gethash "evidence" (gethash "grounding" (gethash "claim" (aref claims 1)))) 0))))
        (setf (gethash "review" step) review (gethash "request_digest" step) (gethash "request_digest" review-input))
        (let ((result (al-run bundle)))
          (am-check "actual model-session wire applies reviewed ordinary episode" (equal "admitted" (gethash "formation_outcome" (gethash "application" (gethash "value" result)))) )
          (am-check "held-out exact retrieval succeeds after adapter review" (= 1 (length (gethash "rows" (aref (gethash "queries" result) 0)))))
          (am-check "held-out unrelated query stays empty" (zerop (length (gethash "rows" (aref (gethash "queries" result) 2))))))
        (let ((bad (%cg-detach step)))
          (setf (gethash "request_digest" bad) (%cg-sha256 "wrong"))
          (am-check "review cannot be rebound to a different extraction request"
                    (am-error (lambda () (lab-authority-step graph bad 0 (gethash "ontology_revision" raw))))))
        (let ((bad (%cg-detach step)))
          (setf (gethash "claim_reviews" (gethash "review" bad)) #())
          (am-check "missing ordinary reviews are not fabricated"
                    (am-error (lambda () (lab-authority-step graph bad 0 (gethash "ontology_revision" raw))))))
        (let ((bad (%cg-detach step)))
          (setf (gethash "verdict" (aref (gethash "claim_reviews" (gethash "review" bad)) 0)) "UNSUPPORTED")
          (am-check "ordinary unsupported claim rejects whole lab batch"
                    (equal "rejected" (gethash "status" (lab-authority-step graph bad 0 (gethash "ontology_revision" raw))))))
        (am-check "failed and rejected reviews made no graph changes" (zerop (context-graph-entity-count graph)))
        (lab-authority-step graph step 0 (gethash "ontology_revision" raw))
        (multiple-value-bind (correction boundary) (lab-authority-context graph (am-episode "episode:second" "The stored name is wrong; use Mira." 101) 1)
          (declare (ignore boundary))
          (multiple-value-bind (unused correction-raw view) (at-fixture 1)
            (declare (ignore unused view))
            (let* ((target (aref (gethash "eligible_entities" correction) 0))
                   (entity (aref (gethash "entities" correction-raw) 0)) (revision (aref (gethash "entity_revisions" correction-raw) 0)))
              (setf (gethash "evidence_status" entity) "unreviewed" (gethash "evidence_note" entity) "pending independent review"
                    (gethash "existing_node_id" entity) (gethash "node_id" target)
                    (gethash "target_entity_id" revision) (gethash "entity_id" target) (gethash "target_node_id" revision) (gethash "node_id" target)
                    (gethash "expected_revision_digest" revision) (gethash "revision_digest" target)
                    (gethash "target_scope_id" revision) (gethash "scope_id" (aref (gethash "correction_scopes" correction) 0))
                    (gethash "source_id" (aref (gethash "evidence" (gethash "grounding" revision)) 0)) "episode:second")
              (let* ((next (%cg-object "episode" (am-episode "episode:second" "The stored name is wrong; use Mira." 101)
                                      "proposal" correction-raw "review" :null "request_digest" :null))
                     (next-bundle (%cg-detach bundle)))
                (setf (gethash "history" next-bundle) (vector step) (gethash "step" next-bundle) next
                      (gethash "queries" next-bundle) #("Mira" "Mina" "cat"))
                (let* ((spec (al-run next-bundle)) (response (am-review correction correction-raw)))
                  (am-check "one review request carries the complete correction scope"
                            (= 1 (length (gethash "revisions" (gethash "revision_request" (gethash "input" (gethash "value" spec)))))))
                  (setf (gethash "review" next) response (gethash "request_digest" next) (gethash "request_digest" spec))
                  (am-save-cli-replay step next)
                  (let ((missing (%cg-detach next)))
                    (setf (gethash "revision_reviews" (gethash "review" missing)) #())
                    (am-check "omitted conversational review cannot become an empty approval"
                              (am-error (lambda () (lab-authority-step graph missing 1 (gethash "ontology_revision" raw))))))
                  (let ((result (al-run next-bundle)))
                    (am-check "actual adapter correction resolves the original enduring ID"
                              (equal (gethash "entity_id" target) (gethash "entity_id" (gethash "object" (aref (gethash "rows" (aref (gethash "queries" result) 0)) 0)))))
                    (am-check "old name does not regain current-name support through adapter"
                              (zerop (length (gethash "rows" (aref (gethash "queries" result) 1)))))))))))))))
(let ((result (lab-authority-input-result (lambda () (%cg-authority-fail "PROPOSAL_INVALID")))))
  (am-check "expected input refusal has structured code and no admitted value"
            (and (equal "rejected" (gethash "status" result))
                 (eq :null (gethash "value" result))
                 (equal "PROPOSAL_INVALID" (gethash "code" (aref (gethash "diagnostics" result) 0))))))
(am-check "unexpected internal errors remain failures"
          (handler-case (progn (lab-authority-input-result (lambda () (error "synthetic internal failure"))) nil)
            (simple-error () t)))
(multiple-value-bind (partition ignored participants) (as-fixture)
  (declare (ignore ignored participants))
  (dolist (invalid '("version" "entity"))
    (let* ((raw (am-proposal))
           (bundle (%cg-object "schema_version" 2 "authority_operation" "model-session"
                               "source_kind" "synthetic-controlled" "ontology" (gethash "ontology" partition)
                               "ontology_revision" (gethash "ontology_revision" raw) "history" #() "queries" #("cat")
                               "step" (%cg-object "episode" (am-episode "episode:first" "I own a cat named Mina." 100)
                                                  "proposal" raw "review" :null "request_digest" :null))))
      ;; Reproduce malformed provider shapes without relying on private receipt IDs.
      (if (equal invalid "version") (setf (gethash "schema_version" raw) 1)
          (setf (gethash "identity_action" (aref (gethash "entities" raw) 0)) "CREATE"))
      (let ((result (al-run bundle)))
        (am-check (format nil "actual subprocess reports invalid ~a without crashing" invalid)
                  (and (equal "rejected" (gethash "status" result))
                       (eq :null (gethash "value" result))
                       (equal (if (equal invalid "version") "PROPOSAL_INVALID" "ENTITY_INVALID")
                              (gethash "code" (aref (gethash "diagnostics" result) 0)))))))))
(format t "MODEL-ADAPTER ~d passed, 0 failed~%" *model-adapter-checks*)
