;;;; harness: bare
(load (merge-pathnames "context-graph-identity-pages-tests.lisp" *load-truename*))
(in-package :pai.context-graph)

(let* ((ontology (gethash "ontology" (as-fixture))) (graph (make-context-graph ontology))
       (quote "I own a cat named Mina.")
       (episode (sm-episode "identity-owner-source" (concatenate 'string (make-string 1600 :initial-element #\x) " " quote) 100))
       (mentions (vector (%cg-object "mention" "mention_1" "source" "source_1" "quote" quote)))
       (owner (%cgi-owner-create graph "lab-agent" "lab-persona"))
       (events nil) (sequence 10) (calls 0) (pause t))
  (multiple-value-bind (seed boundary) (lab-authority-context graph episode 0)
    (let* ((revision "personal-context-core-glm53-v1.2")
           (raw (%cgs-expand seed ontology revision (sm-proposal))) (review (sm-review seed raw)))
      (%cgm-apply-reviewed graph boundary seed raw review revision
        (%cg-object "request_digest" (%cg-authority-digest "model-review-input" (gethash "value" (%cgm-review-input seed raw revision)))
                    "response_digest" (%cg-authority-digest "model-review-output" review))))
    (dotimes (i 59)
      (%cg-authority-new-entity graph
        (%cg-object "local_ref" (format nil "alternative-~d" i) "kind" "organism" "label" "Mina"
                    "aliases" #() "classifications" #("cat")) seed #() (make-hash-table :test #'equal)))
    (setf (context-graph-entity-scan-index graph)
          (coerce (sort (loop for id being the hash-keys of (context-graph-entities graph) collect id) #'string<) 'vector)
          (context-graph-projection-digest graph) nil))
  (labels ((source (g id now) (declare (ignore now)) (assert (= 1 id)) (lab-authority-context g episode 1))
           (append-event (type payload cause)
             (let ((e (context-graph-runtime-read-json (context-graph-runtime-json
                         (%cg-object "id" (incf sequence) "agent_id" "lab-agent" "type" type "payload" payload "caused_by" cause)))))
               (push e events) e))
           (model (phase spec digest opened ceiling)
             (declare (ignore digest opened)) (assert (= 5 ceiling))
             (assert (equal (gethash "text" (aref (gethash "sources" (gethash "input" spec)) 0))
                            (gethash "text" (aref (gethash "sources" episode) 0))))
             (when (and pause (equal phase "identity-page-2"))
               (setf pause nil) (return-from model (values :paused-budget 0)))
             (incf calls)
             (values
               (if (equal phase "identity-resolve")
                   (%cg-object "resolutions" (vector (%cg-object "mention" "mention_1" "candidate" :null)))
                   (let ((candidate (cond ((equal phase "identity-page-1") "candidate_1")
                                          ((equal phase "identity-page-2") "candidate_13"))))
                     (%cg-object "mentions" (vector (%cg-object "mention" "mention_1" "status" (if candidate "possible" "none")
                                                               "candidates" (if candidate (vector candidate) #())))))) 2)))
    (let* ((full (source graph 1 100)) (before (%cg-authority-watermark graph "lab-agent" "lab-persona"))
           (discovery (%cgi-discover graph full 0 mentions)))
      (assert (sm-error (lambda () (%cgro-batch-context graph full 0 "staged" "bounded-v4")) "IDENTITY_CANDIDATE_LIMIT"))
      (assert (= 60 (gethash "exact_match_count" discovery)))
      (assert (= 60 (gethash "selected_count" discovery)))
      (assert (= 5 (length (gethash "pages" (gethash "plan" discovery)))))
      (assert (%cg-authority-equal-p discovery (%cgi-discover graph full 0 mentions)))
      (assert (sm-error (lambda () (%cgi-owner-open owner #'source #'append-event 1 0 mentions 29 5 100)) "IDENTITY_OPEN_INVALID"))
      (assert (null events))
      (let* ((opened (gethash "id" (%cgi-owner-open owner #'source #'append-event 1 0 mentions 30 5 100)))
             (open-event (first events)))
        (assert (equal "paused-budget" (gethash "status" (%cgi-owner-run owner #'source #'append-event #'model opened))))
        (assert (= 1 calls))
        (assert (= 2 (%cgi-owner-exposure owner opened)))
        (setf owner (%cgi-owner-create graph "lab-agent" "lab-persona"))
        (dolist (event (reverse events)) (%cgi-owner-consume owner event #'source))
        (assert (equal "complete" (gethash "status" (%cgi-owner-run owner #'source #'append-event #'model opened))))
        (assert (= 6 calls))
        (assert (= 12 (%cgi-owner-exposure owner opened)))
        (let ((fresh (%cgi-owner-create graph "lab-agent" "lab-persona")))
          (dolist (event (reverse events)) (%cgi-owner-consume fresh event #'source))
          (assert (= 12 (%cgi-owner-exposure fresh opened)))
          (assert (%cg-authority-equal-p (gethash opened (cgi-owner-terminals owner)) (gethash opened (cgi-owner-terminals fresh)))))
        (assert (= 6 calls))
        ;; Completion and discovery manifests cannot be substituted in replay.
        (let* ((fresh (%cgi-owner-create graph "lab-agent" "lab-persona"))
               (bad (%cg-detach open-event)) (record (%cgro-record bad)))
          (setf (gethash "selected_count" (gethash "discovery" record)) 1
                (gethash "record_json" (gethash "payload" bad)) (context-graph-runtime-json record))
          (assert (sm-error (lambda () (%cgi-owner-consume fresh bad #'source)) "IDENTITY_OPEN_INVALID"))
          (setf (gethash "selected_count" (gethash "discovery" record)) 60
                (gethash "label" (aref (gethash "eligible_entities" (aref (gethash "contexts" (gethash "plan" (gethash "discovery" record))) 0)) 0)) "Forged identity"
                (gethash "record_json" (gethash "payload" bad)) (context-graph-runtime-json record))
          (assert (sm-error (lambda () (%cgi-owner-consume fresh bad #'source)) "IDENTITY_OPEN_INVALID")))
        (let* ((fresh (%cgi-owner-create graph "lab-agent" "lab-persona")) (ordered (reverse events))
               (bad (%cg-detach (third ordered))) (record (%cgro-record bad)))
          (dolist (event (subseq ordered 0 2)) (%cgi-owner-consume fresh event #'source))
          (setf (gethash "charged_microusd" record) 6
                (gethash "record_json" (gethash "payload" bad)) (context-graph-runtime-json record))
          (assert (sm-error (lambda () (%cgi-owner-consume fresh bad #'source)) "IDENTITY_RESPONSE_INVALID"))
          (assert (= 5 (%cgi-owner-exposure fresh opened))))
        (let* ((fresh (%cgi-owner-create graph "lab-agent" "lab-persona")) (ordered (reverse events))
               (bad (%cg-detach (second ordered))) (record (%cgro-record bad)))
          (%cgi-owner-consume fresh (first ordered) #'source)
          (setf (gethash "phase" record) "identity-page-2"
                (gethash "record_json" (gethash "payload" bad)) (context-graph-runtime-json record))
          (assert (sm-error (lambda () (%cgi-owner-consume fresh bad #'source)) "IDENTITY_PHASE_ORDER_INVALID")))
        (let* ((fresh (%cgi-owner-create graph "lab-agent" "lab-persona"))
               (ordered (reverse events)) (bad (%cg-detach (car (last ordered)))) (record (%cgro-record bad)))
          (dolist (event (butlast ordered)) (%cgi-owner-consume fresh event #'source))
          (setf (gethash "candidate" (aref (gethash "resolutions" (gethash "result" record)) 0)) "candidate_1"
                (gethash "record_json" (gethash "payload" bad)) (context-graph-runtime-json record))
          (assert (sm-error (lambda () (%cgi-owner-consume fresh bad #'source)) "IDENTITY_COMPLETION_BINDING_INVALID")))
        ;; A broken provider ceiling is recorded truthfully and stops all calls.
        (let ((overrun (%cgi-owner-create graph "lab-agent" "lab-persona")) (overrun-events nil) (attempts 0))
          (%cgi-owner-consume overrun open-event #'source)
          (let ((result (%cgi-owner-run overrun #'source
            (lambda (type payload cause)
              (let ((event (context-graph-runtime-read-json (context-graph-runtime-json
                         (%cg-object "id" (incf sequence) "agent_id" "lab-agent" "type" type "payload" payload "caused_by" cause)))))
                (push event overrun-events) event))
            (lambda (phase spec digest id ceiling) (declare (ignore phase spec digest id ceiling))
              (incf attempts) (values (%cg-object "mentions" #()) 37)) opened)))
            (assert (equal "IDENTITY_CHARGE_OVERRUN" (gethash "reason" result))))
          (assert (= 1 attempts))
          (assert (= 37 (%cgi-owner-exposure overrun opened)))
          (let ((fresh (%cgi-owner-create graph "lab-agent" "lab-persona")))
            (%cgi-owner-consume fresh open-event #'source)
            (dolist (event (reverse overrun-events)) (%cgi-owner-consume fresh event #'source))
            (assert (= 37 (%cgi-owner-exposure fresh opened)))))
        ;; Crash after durable request: no retry, held exposure remains conservative.
        (let ((crashed (%cgi-owner-create graph "lab-agent" "lab-persona")) (ordered (reverse events))
              (failed-events nil))
          (dolist (event (subseq ordered 0 2)) (%cgi-owner-consume crashed event #'source))
          (assert (equal "failed" (gethash "status" (%cgi-owner-run crashed #'source
            (lambda (type payload cause)
              (let ((event (%cg-object "id" (incf sequence) "agent_id" "lab-agent" "type" type "payload" payload "caused_by" cause)))
                (push event failed-events) event)) #'model opened))))
          (assert (= 6 calls))
          (assert (= 5 (%cgi-owner-exposure crashed opened)))
          (assert (equal "IDENTITY_CALL_OUTCOME_AMBIGUOUS" (gethash "reason" (%cgro-record (first failed-events)))))))
      (assert (%cg-authority-equal-p before (%cg-authority-watermark graph "lab-agent" "lab-persona")))
      ;; Artificial fixture mutation proves old plans are not silently refreshed.
      (let* ((drift (%cgi-owner-create graph "lab-agent" "lab-persona")) (opened-event (first (reverse events)))
             (opened (gethash "id" opened-event)))
        (%cgi-owner-consume drift opened-event #'source)
        (dotimes (i 37)
          (%cg-authority-new-entity graph
            (%cg-object "local_ref" (format nil "overflow-~d" i) "kind" "organism" "label" "Mina"
                        "aliases" #() "classifications" #("cat")) full #() (make-hash-table :test #'equal)))
        (setf (context-graph-entity-scan-index graph)
              (coerce (sort (loop for id being the hash-keys of (context-graph-entities graph) collect id) #'string<) 'vector)
              (context-graph-projection-digest graph) nil)
        (let ((result (%cgi-owner-run drift #'source #'append-event #'model opened)))
          (assert (equal "IDENTITY_GRAPH_CHANGED" (gethash "reason" result))))
        (assert (= 6 calls))
        (assert (sm-error (lambda () (%cgi-discover graph (source graph 1 100) 0 mentions)) "IDENTITY_CANDIDATE_LIMIT"))))))
(format t "IDENTITY-OWNER 60-candidate discovery, durable budget pause/resume, cold receipts, tamper refusal, ambiguous-call exposure and zero graph writes passed~%")
