;;;; harness: bare
(load (merge-pathnames "context-graph-full-source-candidates-tests.lisp" *load-truename*))
(in-package :pai.context-graph)

(let* ((ontology (gethash "ontology" (as-fixture))) (graph (make-context-graph ontology))
       (quote "I own a cat named Mina.")
       (episode (sm-episode "paged-identity" (concatenate 'string (make-string 1600 :initial-element #\x) " " quote) 100)))
  (multiple-value-bind (seed boundary) (lab-authority-context graph episode 0)
    (let* ((revision "personal-context-core-glm53-v1.2")
           (raw (%cgs-expand seed ontology revision (sm-proposal))) (review (sm-review seed raw)))
      (%cgm-apply-reviewed graph boundary seed raw review revision
        (%cg-object "request_digest" (%cg-authority-digest "model-review-input" (gethash "value" (%cgm-review-input seed raw revision)))
                    "response_digest" (%cg-authority-digest "model-review-output" review))))
    (dotimes (i 35)
      (%cg-authority-new-entity graph
        (%cg-object "local_ref" (format nil "alternative-~d" i) "kind" "organism" "label" "Mina"
                    "aliases" #() "classifications" #("cat")) seed #() (make-hash-table :test #'equal)))
    (setf (context-graph-entity-scan-index graph)
          (coerce (sort (loop for id being the hash-keys of (context-graph-entities graph) collect id) #'string<) 'vector)
          (context-graph-projection-digest graph) nil))
  (multiple-value-bind (full ignored) (lab-authority-context graph episode 1)
    (declare (ignore ignored))
    (let* ((context (%cgro-batch-context graph full 0 "staged" "bounded-v4"))
           (pages (map 'vector (lambda (i) (let ((copy (%cg-detach context)))
                    (setf (gethash "eligible_entities" copy) (subseq (gethash "eligible_entities" copy) (* i 12) (* (1+ i) 12))) copy)) #(0 1 2)))
           (mentions (vector (%cg-object "mention" "mention_1" "source" "source_1" "quote" quote)))
           (plan (%cgi-plan pages mentions))
           (before (%cg-authority-watermark graph "lab-agent" "lab-persona"))
           (cache (make-hash-table :test #'equal)) (calls 0) (pause t))
      (labels ((row (status candidates) (%cg-object "mentions" (vector (%cg-object "mention" "mention_1" "status" status "candidates" candidates))))
               (answer (phase)
                 (cond ((equal phase "identity-page-1") (row "possible" #("candidate_1")))
                       ((equal phase "identity-page-2") (row "possible" #("candidate_13")))
                       ((equal phase "identity-page-3") (row "none" #()))
                       (t (%cg-object "resolutions" (vector (%cg-object "mention" "mention_1" "candidate" :null))))))
               (port (phase spec digest)
                 ;; Simulated durable receipt port; no provider access.
                 (let ((saved (gethash phase cache)))
                   (when saved
                     (unless (equal digest (car saved)) (%cg-authority-fail "TEST_RECEIPT_DIGEST_MISMATCH"))
                     (return-from port (%cg-detach (cdr saved)))))
                 (assert (equal (gethash "text" (aref (gethash "sources" (gethash "input" spec)) 0))
                                (gethash "text" (aref (gethash "sources" (gethash "source_packet" context)) 0))))
                 (when (and pause (equal phase "identity-page-2"))
                   (setf pause nil) (return-from port :paused-budget))
                 (incf calls)
                 (let ((response (context-graph-runtime-read-json (context-graph-runtime-json (answer phase)))))
                   (setf (gethash phase cache) (cons digest response)) response)))
        (assert (sm-error (lambda () (%cgi-run pages mentions #'port :max-calls 3)) "IDENTITY_CALL_LIMIT"))
        (assert (zerop calls))
        (assert (eq :paused-budget (%cgi-run pages mentions #'port)))
        (assert (= 1 calls))
        (let ((result (%cgi-run pages mentions #'port)))
          (assert (= 4 calls))
          (assert (equal "unreviewed" (gethash "status" result)))
          (assert (eq :null (gethash "candidate" (aref (gethash "resolutions" result) 0))))
          (assert (%cg-authority-equal-p result (%cgi-run pages mentions #'port)))
          (assert (= 4 calls)))
        (let ((changed (%cg-detach mentions)))
          (setf (gethash "quote" (aref changed 0)) "Mina")
          (assert (sm-error (lambda () (%cgi-run pages changed #'port)) "TEST_RECEIPT_DIGEST_MISMATCH")))
        (let ((attempts 0))
          (assert (sm-error (lambda () (%cgi-run pages mentions
                     (lambda (phase spec digest) (declare (ignore phase spec digest))
                       (incf attempts) (%cg-object "mentions" #())))) "IDENTITY_PAGE_RESPONSE_INVALID"))
          (assert (= 1 attempts)))
        (assert (sm-error (lambda () (%cgi-check-page plan 0 (row "possible" #("candidate_13")))) "IDENTITY_PAGE_RESPONSE_INVALID"))
        (assert (sm-error (lambda () (%cgi-check-page plan 0 (row "possible" #("candidate_1" "candidate_1")))) "IDENTITY_PAGE_RESPONSE_INVALID"))
        (assert (sm-error (lambda () (%cgi-check-page plan 0 (row "none" #("candidate_1")))) "IDENTITY_PAGE_RESPONSE_INVALID"))
        (let* ((raw (row "none" #("candidate_1")))
               (*cgi-conservative-page-conflicts-p* t)
               (normalized (%cgi-normalize-page-response raw)))
          (assert (equal "none" (gethash "status" (aref (gethash "mentions" raw) 0))))
          (assert (equal "uncertain" (gethash "status" (aref (gethash "mentions" normalized) 0))))
          (assert (equalp #("candidate_1") (gethash "candidates" (aref (gethash "mentions" normalized) 0))))
          (%cgi-check-page plan 0 normalized)
          ;; Normalization is deliberately narrow: it cannot repair a positive
          ;; status lacking candidates or any malformed schema.
          (assert (sm-error (lambda ()
                              (%cgi-check-page plan 0
                                (%cgi-normalize-page-response (row "possible" #()))))
                            "IDENTITY_PAGE_RESPONSE_INVALID")))
        (let ((*cgi-conservative-page-conflicts-p* t) (resolution-saw-uncertainty nil))
          (let ((result (%cgi-run pages mentions
                          (lambda (phase spec digest)
                            (declare (ignore digest))
                            (cond
                              ((equal phase "identity-page-1") (row "none" #("candidate_1")))
                              ((search "identity-page-" phase) (row "none" #()))
                              (t
                               (setf resolution-saw-uncertainty
                                     (eq :true (gethash "comparison_uncertain"
                                                 (aref (gethash "comparisons" (gethash "input" spec)) 0))))
                               (%cg-object "resolutions"
                                 (vector (%cg-object "mention" "mention_1" "candidate" :null)))))))))
            (assert resolution-saw-uncertainty)
            (assert (eq :null (gethash "candidate" (aref (gethash "resolutions" result) 0))))))
        (assert (sm-error (lambda () (%cgi-resolution-spec plan (vector (answer "identity-page-1")))) "IDENTITY_PAGES_INCOMPLETE"))
        (let* ((responses (vector (row "uncertain" #("candidate_1")) (row "possible" #("candidate_13")) (row "none" #())))
               (schema (gethash "schema" (gethash "value" (%cgi-resolution-spec plan responses)))))
          (assert (not (%cgs-schema-valid-p (%cg-object "resolutions" (vector (%cg-object "mention" "mention_1" "candidate" "candidate_13"))) schema))))
        (assert (sm-error (lambda () (%cgi-resolution-spec plan
          (map 'vector (lambda (i) (row "possible" (map 'vector (lambda (c) (gethash "candidate" c)) (aref (gethash "pages" plan) i)))) #(0 1 2))))
          "IDENTITY_RESOLUTION_LIMIT"))
        ;; A positive selection is allowed, but cannot itself admit or mutate.
        (let ((selected (%cgi-run pages mentions
                          (lambda (phase spec digest) (declare (ignore spec digest))
                            (if (equal phase "identity-resolve")
                                (%cg-object "resolutions" (vector (%cg-object "mention" "mention_1" "candidate" "candidate_13")))
                                (answer phase))))))
          (assert (equal "candidate_13" (gethash "candidate" (aref (gethash "resolutions" selected) 0)))))
        (let ((bad (%cg-detach mentions)))
          (setf (gethash "quote" (aref bad 0)) "Not in the source.")
          (assert (sm-error (lambda () (%cgi-run pages bad #'port)) "IDENTITY_MENTION_INVALID")))
        (assert (sm-error (lambda () (%cgi-plan (vector (aref pages 0) (aref pages 0)) mentions)) "IDENTITY_PAGE_DUPLICATE"))
        (let ((two (vector (aref mentions 0) (%cg-object "mention" "mention_2" "source" "source_1" "quote" "Mina"))))
          (let* ((normalized (%cgi-run pages two
            (lambda (phase spec digest) (declare (ignore spec digest))
              (if (equal phase "identity-resolve")
                  (%cg-object "resolutions" (vector (%cg-object "mention" "mention_1" "candidate" :null)
                                                     (%cg-object "mention" "mention_1" "candidate" :null)))
                  (%cg-object "mentions" (vector (%cg-object "mention" "mention_1" "status" "none" "candidates" #())
                                                 (%cg-object "mention" "mention_2" "status" "none" "candidates" #())))))))
                 (resolved (gethash "resolutions" normalized)))
            ;; Collision normalization preserves neither an ambiguous selection
            ;; nor a missing identity; both rows must be explicit unresolved.
            (assert (= 2 (length resolved)))
            (assert (equalp #("mention_1" "mention_2")
                            (map 'vector (lambda (row) (gethash "mention" row)) resolved)))
            (assert (every (lambda (row) (eq :null (gethash "candidate" row))) resolved))))
        (assert (%cg-authority-equal-p before (%cg-authority-watermark graph "lab-agent" "lab-persona")))
        ;; A separate, explicit admission path is still required after selection.
        ;; Scripted review establishes enforcement, not model judgment quality.
        (let* ((simple (sm-proposal)) (revision "personal-context-core-glm53-v1.2")
               (entity-count (context-graph-entity-count graph))
               (target (gethash "entity_id" (gethash "descriptor" (aref (gethash "candidates" plan) 12))))
               (known (loop for key being the hash-keys of (%cgs-handles context) using (hash-value entity)
                            when (equal target (gethash "entity_id" entity)) return key)))
          (setf (gethash "new_entities" simple) #()
                (gethash "object" (aref (gethash "facts" simple) 0)) known)
          (multiple-value-bind (unused boundary) (lab-authority-context graph episode 1)
            (declare (ignore unused))
            (setf (gethash "episode_id" boundary) (gethash "episode_id" context))
            (let* ((raw (%cgs-expand context ontology revision simple)) (review (sm-review context raw)))
              (%cgm-apply-reviewed graph boundary context raw review revision
                (%cg-object "request_digest" (%cg-authority-digest "model-review-input" (gethash "value" (%cgm-review-input context raw revision)))
                            "response_digest" (%cg-authority-digest "model-review-output" review)))
              (assert (= entity-count (context-graph-entity-count graph)))
              (assert (plusp (length (gethash "facts" (gethash "context" (%cg-authority-retrieve graph "lab-agent" "lab-persona" "Mina cat"))))))
              (assert (zerop (length (gethash "facts" (gethash "context" (%cg-authority-retrieve graph "lab-agent" "lab-persona" "asteroid")))))))))))))
(format t "IDENTITY-PAGES intact late source, cross-page alternatives, uncertainty, complete receipt replay, pause, schema bounds and zero mutation passed~%")

;; V2 compares mentions with authenticated conversation participants before a
;; new-identity grouping ask.  All names are synthetic and source-local.
(let* ((ontology (gethash "ontology" (as-fixture)))
       (graph (make-context-graph ontology))
       (text "My name is Rowan. Hello active persona. Another Rowan might visit. Atlas is a project.")
       (episode (sm-episode "participant-candidate-fixture" text 600)))
  (multiple-value-bind (full ignored) (lab-authority-context graph episode 0)
    (declare (ignore ignored))
    (let* ((context (%cgro-batch-context graph full 0 "staged" "bounded-v3"))
           (mentions
             (vector (%cg-object "mention" "mention_1" "source" "source_1" "quote" "My name is Rowan")
                     (%cg-object "mention" "mention_2" "source" "source_1" "quote" "Hello active persona")
                     (%cg-object "mention" "mention_3" "source" "source_1" "quote" "Another Rowan")
                     (%cg-object "mention" "mention_4" "source" "source_1" "quote" "Rowan might visit")
                     (%cg-object "mention" "mention_5" "source" "source_1" "quote" "Atlas")))
           (*cgi-participant-candidates-p* t)
           (plan (%cgi-plan (vector context) mentions))
           (cards (aref (gethash "pages" plan) 0))
           (entries (gethash "candidates" plan)))
      (assert (equal "identity-pages-v2" (gethash "protocol" plan)))
      (assert (= 2 (length cards)))
      (assert (equal "operator" (gethash "participant_role" (aref cards 0))))
      (assert (equal "active-persona" (gethash "participant_role" (aref cards 1))))
      (assert (equal "operator" (%cgf-participant-candidate-handle (aref entries 0))))
      (assert (equal "active_persona" (%cgf-participant-candidate-handle (aref entries 1))))
      (assert (search "authenticated conversation participant"
                      (gethash "system" (gethash "value" (%cgi-page-spec plan 0)))))
      (let* ((result
               (%cgi-run (vector context) mentions
                 (lambda (phase spec digest)
                   (declare (ignore spec digest))
                   (if (equal phase "identity-resolve")
                       (%cg-object "resolutions"
                         (vector (%cg-object "mention" "mention_1" "candidate" "candidate_1")
                                 (%cg-object "mention" "mention_2" "candidate" "candidate_2")
                                 (%cg-object "mention" "mention_3" "candidate" :null)
                                 (%cg-object "mention" "mention_4" "candidate" :null)
                                 (%cg-object "mention" "mention_5" "candidate" :null)))
                       (%cg-object "mentions"
                         (vector (%cg-object "mention" "mention_1" "status" "possible" "candidates" #("candidate_1"))
                                 (%cg-object "mention" "mention_2" "status" "possible" "candidates" #("candidate_2"))
                                 (%cg-object "mention" "mention_3" "status" "none" "candidates" #())
                                 (%cg-object "mention" "mention_4" "status" "uncertain" "candidates" #())
                                 (%cg-object "mention" "mention_5" "status" "none" "candidates" #())))))))
             (resolved (gethash "resolutions" result)))
        (assert (equal "candidate_1" (gethash "candidate" (aref resolved 0))))
        (assert (equal "candidate_2" (gethash "candidate" (aref resolved 1))))
        (assert (eq :null (gethash "candidate" (aref resolved 2))))
        (assert (eq :null (gethash "candidate" (aref resolved 3))))
        (assert (eq :null (gethash "candidate" (aref resolved 4)))))
      (let* ((*cgf-protocol* "identity-formation-v8")
             (eligible '("mention_3" "mention_5"))
             (valid (%cg-object "groups"
                      (vector (%cg-object "mentions" #("mention_3") "source" "source_1" "quote" "Another Rowan")
                              (%cg-object "mentions" #("mention_5") "source" "source_1" "quote" "Atlas is a project"))))
             (bad (%cg-object "groups"
                    (vector (%cg-object "mentions" #("mention_5" "mention_3")
                                        "source" "source_1" "quote" "Another Rowan")))))
        (assert (= 2 (length (%cgf-groups context mentions eligible valid))))
        (assert (sm-error (lambda () (%cgf-groups context mentions eligible bad))
                          "FORMATION_GROUP_REPRESENTATIVE_INVALID"))))))
(format t "IDENTITY-PAGES-V2 authenticated participant candidates, direct handles, distinct third party, hypothetical deferral and representative evidence passed~%")
