;;;; harness: bare
(require :asdf)
(unless (find-package :ql) (load (or (uiop:getenv "PAI_QUICKLISP_SETUP") "/opt/quicklisp/setup.lisp")))
(asdf:load-asd (merge-pathnames "../pai-context-graph.asd" *load-truename*))
(asdf:load-system :pai-context-graph)
(in-package :pai.context-graph)
(defvar *authority-scope-checks* 0)
(defun as-check (name value)
  (unless value (error "FAIL ~a" name))
  (incf *authority-scope-checks*) (format t "PASS ~a~%" name))
(load (merge-pathnames "fixtures/context-graph-authority-fixtures.lisp" *load-truename*))
(defun as-scope (result) (aref (gethash "scopes" (gethash "value" result)) 0))
(multiple-value-bind (view policy participants) (as-fixture)
  (let* ((before (%cg-authority-canonical-json (vector view policy participants)))
         (result (context-graph-build-correction-scopes view policy participants)) (scope (as-scope result)))
    (as-check "positive scope enumerates same-name alternatives" (equalp #("entity:000" "entity:001") (gethash "candidate_entity_ids" scope)))
    (as-check "scope completeness is explicit" (eq :true (gethash "complete" scope)))
    (as-check "claims examined once, not candidate rank" (= 2 (gethash "examined_claim_count" (gethash "value" result))))
    (as-check "historical anchors retained" (= 2 (length (gethash "anchor_claims" scope))))
    (as-check "scope leaves source view unchanged" (equal before (%cg-authority-canonical-json (vector view policy participants))))
    (setf (gethash "label" (aref (gethash "eligible_entities" (gethash "value" result)) 0)) "Changed")
    (as-check "scope results detached" (equal before (%cg-authority-canonical-json (vector view policy participants))))))
(dolist (mutation '("negative" "reported-speech" "derived" "inference" "retired"))
  (multiple-value-bind (view policy participants) (as-fixture 1)
    (let* ((claim (aref (gethash "operator_adjacency" view) 0))
           (key (cond ((equal mutation "negative") "polarity") ((equal mutation "reported-speech") "scope")
                      ((equal mutation "derived") "source_basis") ((equal mutation "inference") "evidence_status") (t "status"))))
      (setf (gethash key claim) mutation)
      (as-check mutation (zerop (length (gethash "candidate_entity_ids" (as-scope (context-graph-build-correction-scopes view policy participants)))))))))
(multiple-value-bind (view policy participants) (as-fixture 17)
  (let ((scope (as-scope (context-graph-build-correction-scopes view policy participants))))
    (as-check "seventeenth candidate makes scope incomplete" (eq :false (gethash "complete" scope)))
    (as-check "candidate output stays at sixteen" (= 16 (length (gethash "candidate_entity_ids" scope))))))
(multiple-value-bind (view policy participants) (as-fixture 1)
  (setf (gethash "adjacency_complete" view) :false)
  (as-check "upstream incomplete enumeration cannot become singleton authority"
            (eq :false (gethash "complete" (as-scope (context-graph-build-correction-scopes view policy participants))))))
(multiple-value-bind (view policy participants) (as-fixture 1)
  (let* ((claim (aref (gethash "operator_adjacency" view) 0))
         (claims (loop for i below 4097 collect
                   (let ((copy (%cg-detach claim))) (setf (gethash "fact_id" copy) (format nil "fact:~5,'0d" i)) copy))))
    (setf (gethash "operator_adjacency" view) (coerce claims 'vector))
    (let* ((result (context-graph-build-correction-scopes view policy participants)) (scope (as-scope result)))
      (as-check "4097 adjacency claims report incomplete" (eq :false (gethash "complete" scope)))
      (as-check "adjacency examinations bounded at 4096" (= 4096 (gethash "examined_claim_count" (gethash "value" result))))
      (as-check "two retained anchors do not multiply candidates" (and (= 2 (length (gethash "anchor_claims" scope)))
                                                                                   (= 1 (length (gethash "candidate_entity_ids" scope))))))))
(multiple-value-bind (view policy participants) (as-fixture 1)
  (setf (gethash "through_event_id" (aref (gethash "operator_adjacency" view) 0)) 11)
  (as-check "proposed/current episode cannot manufacture historical authority"
            (handler-case (progn (context-graph-build-correction-scopes view policy participants) nil)
              (context-graph-authority-input-error () t))))
(multiple-value-bind (view policy participants) (as-fixture 1)
  (setf (gethash "target_kind" (aref (gethash "scope_definitions" policy) 0)) "imaginary-kind")
  (as-check "scope policy validates actual ontology signature"
            (handler-case (progn (context-graph-build-correction-scopes view policy participants) nil)
              (context-graph-authority-input-error () t))))
(format t "AUTHORITY-SCOPE ~d passed, 0 failed~%" *authority-scope-checks*)
