;;;; harness: bare
(require :asdf)
(unless (find-package :ql) (load (or (uiop:getenv "PAI_QUICKLISP_SETUP") "/opt/quicklisp/setup.lisp")))
(asdf:load-asd (merge-pathnames "../pai-context-graph.asd" *load-truename*))
(asdf:load-system :pai-context-graph)
(in-package :pai.context-graph)
(load (merge-pathnames "fixtures/context-graph-authority-fixtures.lisp" *load-truename*))
(defvar *authority-admission-checks* 0)
(defun aa-check (name value)
  (unless value (error "FAIL ~a" name))
  (incf *authority-admission-checks*) (format t "PASS ~a~%" name))
(defun aa-prepared (context raw)
  (gethash "proposal" (gethash "value" (context-graph-prepare-authority context raw))))
(defun aa-decision (context proposal receipt view)
  (context-graph-decide-entity-revision context proposal "revision:one" receipt view))
(defun aa-reason (context proposal receipt view reason)
  (let ((decision (aa-decision context proposal receipt view)))
    (aa-check reason (equal reason (gethash "reason_code" decision)))
    (aa-check "nonaccepting decision carries no grant" (eq :null (gethash "grant" decision))) decision))
(multiple-value-bind (context raw view) (at-fixture)
  (let* ((proposal (aa-prepared context raw)) (review (at-raw-review context proposal))
         (receipt (at-review-receipt context proposal review))
         (before (%cg-authority-canonical-json (vector context proposal view review receipt)))
         (decision (aa-decision context proposal receipt view))
         (batch (%cg-decide-revision-batch context proposal receipt (vector view))))
    (aa-check "conversational correction accepted without a command" (equal "accept" (gethash "outcome" decision)))
    (aa-check "accepted interpretation is not labeled proof" (equal "policy-accepted-interpretation" (gethash "semantic_status" (gethash "grant" decision))))
    (aa-check "complete batch admitted" (equal "admitted" (gethash "formation_outcome" batch)))
    (aa-check "one shared delta and grant" (and (= 1 (length (gethash "revision_deltas" batch))) (= 1 (length (gethash "revision_grants" batch)))))
    (aa-check "reviewed admission leaves inputs unchanged" (equal before (%cg-authority-canonical-json (vector context proposal view review receipt))))
    (aa-check "policy replay is byte deterministic" (equal (%cg-authority-canonical-json batch)
                                                          (%cg-authority-canonical-json (%cg-decide-revision-batch context proposal receipt (vector view)))))
    (setf (gethash "quote" (gethash "evidence" (aref (gethash "revision_grants" batch) 0))) "Changed")
    (aa-check "accepted grants are detached" (equal before (%cg-authority-canonical-json (vector context proposal view review receipt))))))
(multiple-value-bind (context raw view) (at-fixture)
  (let* ((proposal (aa-prepared context raw)) (decision (aa-reason context proposal :null view "REVIEW_UNAVAILABLE")))
    (aa-check "missing review defers without asking a misleading question" (and (equal "defer" (gethash "outcome" decision)) (eq :null (gethash "clarification" decision))))))
(dolist (spec '(("interpretation" "actual-name-change" "CORRECTION_MEANING_UNRESOLVED")
                ("source_reading" "reported" "NOT_A_CORRECTION")
                ("source_reading" "joke" "CORRECTION_MEANING_UNRESOLVED")
                ("source_reading" "hypothetical" "CORRECTION_MEANING_UNRESOLVED")
                ("same_entity" "unsupported" "CORRECTION_MEANING_UNRESOLVED")
                ("replacement_supported" "uncertain" "CORRECTION_MEANING_UNRESOLVED")
                ("competing_interpretation" "present" "CORRECTION_MEANING_UNRESOLVED")))
  (multiple-value-bind (context raw view) (at-fixture)
    (let* ((proposal (aa-prepared context raw)) (review (at-raw-review context proposal)))
      (setf (gethash (first spec) (aref (gethash "reviews" review) 0)) (second spec))
      (aa-reason context proposal (at-review-receipt context proposal review) view (third spec)))))
(multiple-value-bind (context raw view) (at-fixture)
  (setf (gethash "interpretation" (aref (gethash "entity_revisions" raw) 0)) "mere-mention")
  (let* ((proposal (aa-prepared context raw)) (review (at-raw-review context proposal)))
    (setf (gethash "interpretation" (aref (gethash "reviews" review) 0)) "mere-mention")
    (aa-reason context proposal (at-review-receipt context proposal review) view "NOT_A_CORRECTION")))
(dolist (mutation '("second-target" "retarget" "uncertain-alternative" "no-anchor" "wrong-reason"))
  (multiple-value-bind (context raw view) (at-fixture)
    (let* ((proposal (aa-prepared context raw)) (review (at-raw-review context proposal))
           (candidates (gethash "candidate_assessments" (aref (gethash "reviews" review) 0))))
      (cond ((equal mutation "second-target") (setf (gethash "assessment" (aref candidates 1)) "target"))
            ((equal mutation "retarget") (setf (gethash "assessment" (aref candidates 0)) "not-target" (gethash "assessment" (aref candidates 1)) "target"))
            ((equal mutation "uncertain-alternative") (setf (gethash "assessment" (aref candidates 1)) "uncertain"))
            ((equal mutation "no-anchor") (setf (gethash "anchor_fact_ids" (aref candidates 0)) #()))
            ((equal mutation "wrong-reason") (setf (gethash "reason_code" (aref candidates 1)) "insufficient-context")))
      (let ((decision (aa-reason context proposal (at-review-receipt context proposal review) view "TARGET_AMBIGUOUS")))
        (aa-check "ambiguous target yields bounded clarification" (hash-table-p (gethash "clarification" decision)))))))
(dolist (mutation '("missing-candidate" "duplicate-candidate" "foreign-anchor" "unknown-row-key" "forged-proposal-digest"))
  (multiple-value-bind (context raw view) (at-fixture)
    (declare (ignore view))
    (let* ((proposal (aa-prepared context raw)) (review (at-raw-review context proposal))
           (row (aref (gethash "reviews" review) 0)) (candidates (gethash "candidate_assessments" row)))
      (cond ((equal mutation "missing-candidate") (setf (gethash "candidate_assessments" row) (subseq candidates 0 1)))
            ((equal mutation "duplicate-candidate") (setf (gethash "candidate_assessments" row) (vector (aref candidates 0) (aref candidates 0))))
            ((equal mutation "foreign-anchor") (setf (gethash "anchor_fact_ids" (aref candidates 0)) #("fact:00001")))
            ((equal mutation "unknown-row-key") (setf (gethash "confidence" row) 100))
            ((equal mutation "forged-proposal-digest") (setf (gethash "proposal_digest" row) (%cg-sha256 "forged"))))
      (aa-check mutation (handler-case (progn (at-review-receipt context proposal review) nil) (context-graph-authority-input-error () t))))))
(multiple-value-bind (context raw view) (at-fixture)
  (let* ((proposal (aa-prepared context raw)) (receipt (at-review-receipt context proposal (at-raw-review context proposal))))
    (setf (gethash "request_digest" receipt) (%cg-sha256 "forged"))
    (aa-reason context proposal receipt view "REVIEW_BINDING_INVALID")))
(multiple-value-bind (context raw view) (at-fixture)
  (let* ((proposal (aa-prepared context raw)) (receipt (at-review-receipt context proposal (at-raw-review context proposal))))
    (setf (gethash "label" view) "A newer label" (gethash "revision_digest" view) (%cg-revision-descriptor-digest view))
    (aa-reason context proposal receipt view "TARGET_STALE")))
(multiple-value-bind (context raw view) (at-fixture)
  (setf (gethash "complete" (aref (gethash "correction_scopes" context) 0)) :false)
  (let* ((proposal (aa-prepared context raw)) (built (context-graph-build-revision-review-input context proposal)))
    (aa-check "incomplete scope skips review" (equal "incomplete" (gethash "status" built)))
    (aa-reason context proposal :null view "TARGET_CONTEXT_INCOMPLETE")))
(multiple-value-bind (context raw view) (at-fixture)
  (setf (gethash "candidate_scan" context) (%cg-object "complete" :false "examined_count" 1024))
  (let* ((proposal (aa-prepared context raw)) (receipt (at-review-receipt context proposal (at-raw-review context proposal))))
    (aa-check "lexical incompleteness does not erase complete relational scope" (equal "accept" (gethash "outcome" (aa-decision context proposal receipt view))))))
(multiple-value-bind (context raw view) (at-fixture)
  (let ((entity (%cg-detach (aref (gethash "entities" raw) 0))) (revision (%cg-detach (aref (gethash "entity_revisions" raw) 0))))
    (setf (gethash "local_ref" entity) "conflicting" (gethash "local_ref" revision) "conflicting" (gethash "revision_ref" revision) "revision:two"
          (gethash "entities" raw) (vector (aref (gethash "entities" raw) 0) entity)
          (gethash "entity_revisions" raw) (vector (aref (gethash "entity_revisions" raw) 0) revision))
    (let* ((proposal (aa-prepared context raw)) (batch (%cg-decide-revision-batch context proposal :null (vector view))))
      (aa-check "same-identity conflict rejects entire batch before review" (equal "rejected" (gethash "formation_outcome" batch)))
      (aa-check "conflict creates no active grants or deltas" (and (zerop (length (gethash "revision_grants" batch))) (zerop (length (gethash "revision_deltas" batch))))))))
(dolist (second-meaning '("uncertain" "reported"))
  (multiple-value-bind (context raw view) (at-fixture)
    (let* ((target (aref (gethash "eligible_entities" context) 1))
           (view-two (%cg-detach target))
           (entity (%cg-detach (aref (gethash "entities" raw) 0)))
           (revision (%cg-detach (aref (gethash "entity_revisions" raw) 0))))
      (setf (gethash "observed_at" view-two) 200 (gethash "application_id" view-two) "application:one"
            (gethash "local_ref" entity) "second" (gethash "existing_node_id" entity) (gethash "node_id" target)
            (gethash "local_ref" revision) "second" (gethash "revision_ref" revision) "revision:two"
            (gethash "target_entity_id" revision) (gethash "entity_id" target) (gethash "target_node_id" revision) (gethash "node_id" target)
            (gethash "expected_revision_digest" revision) (gethash "revision_digest" target)
            (gethash "entities" raw) (vector entity (aref (gethash "entities" raw) 0))
            (gethash "entity_revisions" raw) (vector revision (aref (gethash "entity_revisions" raw) 0)))
      (let* ((proposal (aa-prepared context raw)) (review (at-raw-review context proposal)))
        (setf (gethash "source_reading" (aref (gethash "reviews" review) 1)) second-meaning)
        (let* ((receipt (at-review-receipt context proposal review))
               (batch (%cg-decide-revision-batch context proposal receipt (vector view view-two))))
          (aa-check "batch semantic failure has correct precedence" (equal (if (equal "reported" second-meaning) "rejected" "deferred")
                                                                          (gethash "formation_outcome" batch)))
          (aa-check "unrelated accepting row retains verdict but no active grant"
                    (and (equal "accept" (gethash "outcome" (aref (gethash "decisions" batch) 0)))
                         (every (lambda (d) (eq :null (gethash "grant" d))) (gethash "decisions" batch))))
          (aa-check "no partial delta escapes a nonadmitted batch"
                    (and (zerop (length (gethash "revision_grants" batch))) (zerop (length (gethash "revision_deltas" batch)))))
          (aa-check "batch decisions sorted independently of provider order"
                    (equal "revision:one" (gethash "revision_ref" (aref (gethash "decisions" batch) 0)))))))))
(multiple-value-bind (context raw view) (at-fixture)
  (let* ((proposal (aa-prepared context raw))
         (source (aref (gethash "sources" (gethash "source_packet" context)) 0))
         (extra (%cg-detach source))
         (padding (make-string 24000 :initial-element (code-char #x754c))))
    ;; Two full source records exceed the byte limit while each remains under
    ;; its character limit. They must not be shortened to fit the review.
    (setf (gethash "text" source) (concatenate 'string (gethash "text" source) padding)
          (gethash "text_sha256" source) (%cg-sha256 (gethash "text" source))
          (gethash "source_id" extra) "source:context" (gethash "text" extra) (concatenate 'string "Context." padding)
          (gethash "resource_id" (gethash "resource_ref" extra)) "event:context"
          (gethash "text_sha256" extra) (%cg-sha256 (gethash "text" extra))
          (gethash "sources" (gethash "source_packet" context)) (vector source extra)
          (gethash "primary_source_ids" context) #("source:correction" "source:context")
          (gethash "context_evidence" (aref (gethash "entity_revisions" proposal) 0))
          (vector (%cg-object "source_id" "source:context" "quote" "Context." "start_char" 0 "end_char" 8)))
    (let ((built (context-graph-build-revision-review-input context proposal)))
      (aa-check "review size measured in UTF-8 bytes" (equal "incomplete" (gethash "status" built)))
      (aa-reason context proposal :null view "REVIEW_CONTEXT_LIMIT"))))
(multiple-value-bind (context raw view) (at-fixture)
  (declare (ignore view))
  (let ((proposal (aa-prepared context raw)))
    (setf (gethash "label" (find "runtime:operator" (gethash "entities" proposal) :test #'equal :key (lambda (e) (gethash "local_ref" e)))) "Forged")
    (aa-check "sealed participant descriptors cannot be forged"
              (handler-case (progn (context-graph-build-revision-review-input context proposal) nil) (context-graph-authority-input-error () t)))))
(format t "AUTHORITY-ADMISSION ~d passed, 0 failed~%" *authority-admission-checks*)
