;;;; harness: bare
(require :asdf)
(unless (find-package :ql) (load (or (uiop:getenv "PAI_QUICKLISP_SETUP") "/opt/quicklisp/setup.lisp")))
(asdf:load-asd (merge-pathnames "../pai-context-graph.asd" *load-truename*))
(asdf:load-system :pai-context-graph)
(in-package :pai.context-graph)
(load (merge-pathnames "fixtures/context-graph-authority-fixtures.lisp" *load-truename*))
(defvar *authority-preparation-checks* 0)
(defun at-check (name value)
  (unless value (error "FAIL ~a" name))
  (incf *authority-preparation-checks*) (format t "PASS ~a~%" name))
(defun at-error-p (context proposal)
  (handler-case (progn (context-graph-prepare-authority context proposal) nil)
    (context-graph-authority-input-error () t)))
(multiple-value-bind (context proposal view) (at-fixture)
  (declare (ignore view))
  (let* ((before (%cg-authority-canonical-json (vector context proposal)))
         (result (context-graph-prepare-authority context proposal))
         (value (gethash "value" result)) (prepared (gethash "proposal" value))
         (citation (aref (gethash "evidence" (gethash "grounding" (aref (gethash "entity_revisions" prepared) 0))) 0)))
    (at-check "full conversational raw input prepares" (equal "accepted" (gethash "status" result)))
    (at-check "source offsets assigned only by runtime" (and (= 0 (gethash "start_char" citation)) (= 35 (gethash "end_char" citation)) ))
    (at-check "revision receipts bind proposed excerpt" (= 1 (length (gethash "span_receipts" value))))
    (at-check "two runtime participants injected during preparation" (= 3 (length (gethash "entities" prepared))))
    (at-check "raw inputs remain unchanged" (equal before (%cg-authority-canonical-json (vector context proposal))))
    (setf (gethash "quote" citation) "Changed")
    (at-check "prepared output detached" (equal before (%cg-authority-canonical-json (vector context proposal))))))
(multiple-value-bind (context proposal view) (at-fixture)
  (declare (ignore view))
  (let ((citation (aref (gethash "evidence" (gethash "grounding" (aref (gethash "entity_revisions" proposal) 0))) 0)))
    (setf (gethash "quote" citation) "The stored name ... use Mira.")
    (let* ((result (context-graph-prepare-authority context proposal)) (receipt (aref (gethash "span_receipts" (gethash "value" result)) 0)))
      (at-check "elided primary correction expands before review" (equal "The stored name is wrong; use Mira." (gethash "quote" (gethash "accepted_span" receipt))))
      (at-check "elision method retained in private receipt" (equal "ellipsis" (gethash "method" (gethash "accepted_span" receipt)))))))
(dolist (mutation '("unknown-context" "unknown-entity" "forged-offsets" "duplicate-revision" "missing-revision"
                    "mismatched-revision" "boolean-null" "foreign-source-binding" "foreign-scope"))
  (multiple-value-bind (context proposal view) (at-fixture)
    (declare (ignore view))
    (let ((revision (aref (gethash "entity_revisions" proposal) 0)) (entity (aref (gethash "entities" proposal) 0)))
      (cond ((equal mutation "unknown-context") (setf (gethash "confidence" context) 100))
            ((equal mutation "unknown-entity") (setf (gethash "confidence" entity) 100))
            ((equal mutation "forged-offsets") (setf (gethash "start_char" (aref (gethash "evidence" (gethash "grounding" revision)) 0)) 0))
            ((equal mutation "duplicate-revision") (setf (gethash "entity_revisions" proposal) (vector revision revision)))
            ((equal mutation "missing-revision") (setf (gethash "entity_revisions" proposal) #()))
            ((equal mutation "mismatched-revision") (setf (gethash "label" entity) "Different"))
            ((equal mutation "boolean-null") (setf (gethash "complete" (gethash "candidate_scan" context)) :null))
            ((equal mutation "foreign-source-binding")
             (setf (gethash "binding_id" (gethash "identity" (aref (gethash "sources" (gethash "source_packet" context)) 0))) "binding:foreign"))
            ((equal mutation "foreign-scope") (setf (gethash "persona_id" (aref (gethash "correction_scopes" context) 0)) "persona:foreign")))
      (at-check mutation (at-error-p context proposal)))))
(multiple-value-bind (context proposal view) (at-fixture)
  (declare (ignore view))
  (setf (gethash "quote" (aref (gethash "evidence" (gethash "grounding" (aref (gethash "entity_revisions" proposal) 0))) 0)) "Not in the source")
  (at-check "unresolved revision cannot fall back to NEW or alias"
            (eq :null (gethash "value" (context-graph-prepare-authority context proposal)))))
(multiple-value-bind (context proposal view) (at-fixture)
  (declare (ignore view))
  (let* ((source (aref (gethash "sources" (gethash "source_packet" context)) 0))
         (temporal (%cg-object "schema_version" 1 "character" "standing-disposition" "occurred_at" :null "valid_from" :null "valid_until" :null))
         (relationship (%cg-object "subject_ref" "runtime:operator" "predicate" "owns" "object_ref" "corrected"
                                    "relationship_action" "ASSERT" "fact" "The operator owns a cat."
                                    "grounding" (%cg-object "schema_version" 2 "scope" "assertion" "polarity" "positive"
                                                            "attributed_to_ref" "runtime:operator" "evidence"
                                                            (vector (%cg-object "source_id" "source:correction" "quote" "The operator owns a cat.")))
                                    "temporal" temporal "evidence_status" "direct" "evidence_note" "synthetic reviewed utterance")))
    (setf (gethash "text" source) (concatenate 'string "The operator owns a cat. " (gethash "text" source))
          (gethash "text_sha256" source) (%cg-sha256 (gethash "text" source))
          (gethash "relationships" proposal) (vector relationship))
    (let* ((result (context-graph-prepare-authority context proposal))
           (rows (gethash "relationships" (gethash "proposal" (gethash "value" result)))))
      (at-check "ordinary grounded relationships prepare alongside correction" (= 1 (length rows)))
      (at-check "ordinary citation offsets are assigned before review"
                (= 0 (gethash "start_char" (aref (gethash "evidence" (gethash "grounding" (aref rows 0))) 0)))))
    (setf (gethash "valid_until" temporal) nil)
    (at-check "legacy NIL is not new-profile temporal null" (at-error-p context proposal))
    (setf (gethash "valid_until" temporal) :null
          (gethash "evidence" (gethash "grounding" relationship)) #())
    (at-check "ordinary claims cannot prepare with empty citations" (at-error-p context proposal))
    (setf (gethash "evidence" (gethash "grounding" relationship)) (vector (%cg-object "source_id" "source:correction" "quote" "Not a source span")))
    (let ((result (context-graph-prepare-authority context proposal)))
      (at-check "unresolved ordinary claim is explicitly omitted before review"
                (and (zerop (length (gethash "relationships" (gethash "proposal" (gethash "value" result)))))
                     (equal "RELATIONSHIP_SPAN_OMITTED" (gethash "code" (aref (gethash "diagnostics" result) 0))))))))
(format t "AUTHORITY-PREPARATION ~d passed, 0 failed~%" *authority-preparation-checks*)
