;;;; harness: bare
(require :asdf)
(unless (find-package :ql)
  (load (or (uiop:getenv "PAI_QUICKLISP_SETUP") "/opt/quicklisp/setup.lisp")))
(asdf:load-asd (pathname (or (uiop:getenv "PAI_CONTEXT_GRAPH_ASD")
                           (merge-pathnames "../pai-context-graph.asd" *load-truename*))))
(asdf:load-system :pai-context-graph :force t)
(in-package :pai.context-graph)
(defvar *gg-pass* 0)
(defvar *gg-fail* 0)
(defun gg-check (name thunk)
  (handler-case
      (if (funcall thunk) (progn (incf *gg-pass*) (format t "PASS ~a~%" name))
          (progn (incf *gg-fail*) (format t "FAIL ~a~%" name)))
    (error (e) (incf *gg-fail*) (format t "FAIL ~a: ~a~%" name e))))
(defun gg-error (thunk) (handler-case (progn (funcall thunk) nil) (error () t)))
(defun gg-graph ()
  (make-context-graph (%cg-object "entity_types" #("person" "concept")
    "edge_types" (vector (%cg-object "name" "uses" "subject_types" #("person")
                                    "object_types" #("concept"))))))
(defun gg-episode (id text)
  (%cg-object "episode_id" id "occurred_at" "2026-01-01T00:00:00Z"
              "learned_at" "2026-01-01T00:00:00Z" "content" text))
(defun gg-packet (text &optional (kind "original-utterance"))
  (%cg-object "schema_version" 1 "sources"
    (vector (%cg-object "source_id" "source:one" "speaker_id" "speaker:one"
                       "kind" kind "text" text "text_sha256" (%cg-sha256 text)))))
(defun gg-proposal (scope text &optional (polarity "positive"))
  (%cg-object "entities"
    (vector (%cg-object "local_ref" "p" "type" "person" "name" "Operator"
                       "aliases" #() "action" "NEW" "existing_id" :null)
            (%cg-object "local_ref" "o" "type" "concept" "name" "Notebook"
                       "aliases" #() "action" "NEW" "existing_id" :null))
    "facts" (vector (%cg-object "subject_ref" "p" "predicate" "uses" "object_ref" "o"
      "fact" text "supersedes_fact_id" :null "evidence_status" "direct"
      "evidence_note" "Controlled source"
      "grounding" (%cg-object "schema_version" 1 "scope" scope "polarity" polarity
        "attributed_to_ref" "p" "evidence" (vector (%cg-object "source_id" "source:one" "quote" text)))))))
(defun gg-apply (graph id scope text &optional (polarity "positive") (kind "original-utterance"))
  (context-graph-apply-episode graph (gg-episode id text) (gg-proposal scope text polarity)
                             :source-packet (gg-packet text kind)))

(gg-check "grounded assertion is readable with original speaker and exact source" (lambda ()
  (let ((g (gg-graph)))
    (gg-apply g "a" "assertion" "I use a notebook.")
    (let* ((r (context-graph-search g "notebook" :claim-policy "grounded-assertions"))
           (f (aref (gethash "facts" r) 0)))
      (and (= 1 (gethash "result_count" r))
           (equal "assertion" (gethash "scope" (gethash "grounding" f)))
           (equal "speaker:one" (gethash "speaker_id" (aref (gethash "sources" (gethash "grounding" f)) 0))))))))
(gg-check "questions and hypothetical premises remain scoped, not factual answers" (lambda ()
  (let ((g (gg-graph)))
    (gg-apply g "q" "question" "Do I use a notebook?")
    (gg-apply g "h" "hypothesis" "If I used a notebook, it might help.")
    (and (= 2 (context-graph-fact-count g))
         (= 0 (gethash "result_count" (context-graph-search g "notebook")))
         (= 2 (gethash "result_count" (context-graph-search g "notebook" :claim-policy "all")))))))
(gg-check "same triple cannot flatten polarity or qualifiers" (lambda ()
  (let ((g (gg-graph)))
    (gg-apply g "p" "assertion" "I use a notebook.")
    (gg-apply g "n" "assertion" "I do not use a notebook." "negative")
    (gg-apply g "d" "assertion" "I use a notebook only on weekends.")
    (= 3 (context-graph-fact-count g)))))
(gg-check "summary evidence cannot become original-source factual authority" (lambda ()
  (let ((g (gg-graph)))
    (gg-apply g "s" "assertion" "Operator uses a notebook." "positive" "generated-summary")
    (= 0 (gethash "result_count" (context-graph-search g "notebook" :claim-policy "grounded-assertions"))))))
(gg-check "prior agent utterance is accepted only as derived authority" (lambda ()
  (let* ((g (gg-graph)) (text "Operator uses a notebook.")
         (packet (gg-packet text "prior-agent-utterance")))
    (setf (gethash "timestamp" (aref (gethash "sources" packet) 0))
          "2026-01-01T00:00:00Z")
    (context-graph-apply-episode g (gg-episode "prior" text)
                                 (gg-proposal "assertion" text)
                                 :source-packet packet)
    (let* ((all (context-graph-search g "notebook" :claim-policy "all"))
           (fact (aref (gethash "facts" all) 0)))
      (and (= 1 (gethash "result_count" all))
           (equal "derived" (gethash "source_basis" (gethash "grounding" fact)))
           (= 0 (gethash "result_count"
                         (context-graph-search g "notebook"
                                               :claim-policy "grounded-assertions"))))))))
(gg-check "changed packet bytes and invented quote fail before mutation" (lambda ()
  (let* ((g (gg-graph)) (p (gg-packet "Original")) (proposal (gg-proposal "assertion" "Original")))
    (setf (gethash "text" (aref (gethash "sources" p) 0)) "Changed")
    (and (gg-error (lambda () (context-graph-apply-episode g (gg-episode "bad" "Original") proposal :source-packet p)))
         (= 0 (context-graph-entity-count g))
         (gg-error (lambda () (context-graph-apply-episode g (gg-episode "bad" "Original")
                                (gg-proposal "assertion" "Invented") :source-packet (gg-packet "Original"))))
         (= 0 (context-graph-fact-count g))))))
(gg-check "compact reads and identity candidates retain scope" (lambda ()
  (let ((g (gg-graph)))
    (gg-apply g "n" "assertion" "I do not use a notebook." "negative")
    (let* ((compact (context-graph-compact-search g "notebook"))
           (candidate (context-graph-entity-candidates g (%cg-object "type" "person" "name" "Operator" "local_ref" "p")))
           (relation (aref (gethash "relationships" (aref (gethash "candidates" candidate) 0)) 0)))
      (and (equal "negative" (gethash "polarity" (gethash "grounding" (aref (gethash "facts" compact) 0))))
           (equal "negative" (gethash "polarity" (gethash "grounding" relation))))))))
(gg-check "later invalid fact rolls back the whole grounded episode" (lambda ()
  (let* ((g (gg-graph)) (p (gg-proposal "assertion" "I use a notebook."))
         (bad (gg-proposal "assertion" "I use a notebook.")))
    (setf (gethash "predicate" (aref (gethash "facts" bad) 0)) "undeclared"
          (gethash "facts" p) (concatenate 'vector (gethash "facts" p) (gethash "facts" bad)))
    (and (gg-error (lambda () (context-graph-apply-episode g (gg-episode "bad" "I use a notebook.") p
                                       :source-packet (gg-packet "I use a notebook."))))
         (= 0 (context-graph-entity-count g)) (= 0 (context-graph-fact-count g))))))
(gg-check "all supporting source kinds contribute to the original-evidence gate" (lambda ()
  (let* ((g (gg-graph)) (text "I use a notebook.") (p (gg-packet text))
         (summary (aref (gethash "sources" (gg-packet text "generated-summary")) 0))
         (proposal (gg-proposal "assertion" text)))
    (setf (gethash "source_id" summary) "source:summary"
          (gethash "sources" p) (concatenate 'vector (gethash "sources" p) (vector summary))
          (gethash "evidence" (gethash "grounding" (aref (gethash "facts" proposal) 0)))
          (vector (%cg-object "source_id" "source:one" "quote" text)
                  (%cg-object "source_id" "source:summary" "quote" text)))
    (context-graph-apply-episode g (gg-episode "mixed" text) proposal :source-packet p)
    (= 0 (gethash "result_count" (context-graph-search g "notebook" :claim-policy "grounded-assertions"))))))
(gg-check "grounded episode replay detects a changed payload" (lambda ()
  (let ((g (gg-graph)))
    (gg-apply g "same-id" "assertion" "I use a notebook.")
    (and (equal "already-applied" (gethash "status" (gg-apply g "same-id" "assertion" "I use a notebook.")))
         (gg-error (lambda () (gg-apply g "same-id" "question" "Do I use a notebook?")))))))
(gg-check "unqualified grounded supersession cannot expire an assertion" (lambda ()
  (let* ((g (gg-graph)) (text "Do I use a notebook?"))
    (gg-apply g "first" "assertion" "I use a notebook.")
    (let* ((prior (aref (gethash "facts" (context-graph-snapshot g)) 0))
           (proposal (gg-proposal "question" text)))
      (setf (gethash "supersedes_fact_id" (aref (gethash "facts" proposal) 0)) (gethash "fact_id" prior))
      (and (gg-error (lambda () (context-graph-apply-episode g (gg-episode "second" text) proposal :source-packet (gg-packet text))))
           (= 1 (gethash "result_count" (context-graph-search g "notebook" :claim-policy "grounded-assertions"))))))))
(format t "~%Grounding: ~d passed, ~d failed.~%" *gg-pass* *gg-fail*)
(when (plusp *gg-fail*) (uiop:quit 1))
