(load "tests/context-graph-identity-formation-tests.lisp")
(in-package :pai.context-graph)
(load "scripts/context-graph-authority-session.lisp")

(defun gf-lab-model (phase spec &key (canonical-label "supported"))
  (let ((response (gf-model phase spec)))
    (when (and (equal phase "review") (equal "identity-formation-review-v2" (gethash "adapter_revision" spec)))
      (let ((rows (make-hash-table :test #'equal)))
        (loop for row across (gethash "claim_reviews" response) do
          (let ((ref (gethash "claim_ref" row)))
            (remhash "claim_ref" row)
            (when (search "entity:" ref)
              (remhash "source_reading" row)
              (dolist (key (rest +cgq-checks+)) (remhash key (gethash "quality_checks" row)))
              (when (%cgf-canonical-label-p)
                (setf (gethash "canonical_label" (gethash "quality_checks" row)) canonical-label)))
            (setf (gethash ref rows) row)))
        (setf (gethash "claim_reviews" response) rows)
        (assert (%cgs-schema-valid-p response (gethash "schema" spec)))
        (let ((bad (%cg-detach response)))
          (setf (gethash "source_reading" (gethash "entity:new_1" (gethash "claim_reviews" bad))) "assertion")
          (assert (not (%cgs-schema-valid-p bad (gethash "schema" spec)))))
        (let ((bad (%cg-detach response)))
          (setf (gethash "time" (gethash "quality_checks" (gethash "relationship:0" (gethash "claim_reviews" bad)))) "not-applicable")
          (assert (not (%cgs-schema-valid-p bad (gethash "schema" spec)))))))
    response))

(dolist (protocol '("identity-formation-session" "identity-formation-v2-session"))
(let* ((ontology (gethash "ontology" (as-fixture)))
       (step (%cg-object "episode" (sm-episode "lab-formation" "I own a cat named Mina." 100) "calls" #()))
       (bundle (%cg-object "authority_operation" protocol "source_kind" "synthetic-controlled" "ontology" ontology
                           "ontology_revision" "personal-context-core-glm53-v1.2"
                           "history" #() "step" step "queries" #("Mina cat" "asteroid")))
       (count 0))
  (loop for result = (lab-identity-session bundle) do
    (when (eq :true (gethash "terminal" result))
      (assert (= 6 count))
      (assert (plusp (length (gethash "facts" (gethash "context" (aref (gethash "queries" result) 0))))))
      (assert (zerop (length (gethash "facts" (gethash "context" (aref (gethash "queries" result) 1))))))
      (return))
    (incf count)
    (assert (<= count 13))
    (setf (gethash "calls" step)
          (concatenate 'vector (gethash "calls" step)
            (vector (%cg-object "phase" (gethash "phase" result) "request_digest" (gethash "request_digest" result)
                                "response" (gf-lab-model (gethash "phase" result) (gethash "value" result)))))))
  (let ((bad (%cg-detach bundle)))
    (setf (gethash "request_digest" (aref (gethash "calls" (gethash "step" bad)) 0)) "forged")
    (assert (sm-error (lambda () (lab-identity-session bad)) "LAB_IDENTITY_RECEIPT_INVALID")))))
(format t "IDENTITY-LAB incremental requests, replay, useful retrieval and tamper rejection passed~%")

(let* ((*cgf-protocol* "identity-formation-v2")
       (ontology (gethash "ontology" (as-fixture))) (graph (make-context-graph ontology))
       (episode (sm-episode "substituted-endpoint" "I own a cat named Mina." 100)))
  (multiple-value-bind (full boundary) (lab-authority-context graph episode 0)
    (let ((envelope (%cgf-generate graph full 0 ontology "personal-context-core-glm53-v1.2"
      (lambda (phase spec digest) (declare (ignore digest))
        (let ((response (gf-lab-model phase spec)))
          (when (equal phase "review")
            (setf (gethash "endpoint_identity" (gethash "quality_checks"
                    (gethash "relationship:0" (gethash "claim_reviews" response)))) "unsupported"))
          response)))))
      (setf (gethash "episode_id" boundary) (gethash "episode_id" (gethash "context" envelope)))
      (%cgf-apply graph boundary full envelope)
      (assert (zerop (context-graph-fact-count graph))))))
(format t "TYPED-REVIEW unsupported endpoint judgment cannot become facts~%")
