(load "tests/context-graph-identity-lab-tests.lisp")
(in-package :pai.context-graph)

(defun gg-model (phase spec distinct quote &key overlap unanchored)
  (cond
    ((equal phase "mentions")
     (%cg-object "mentions" (vector (%cg-object "source" "source_1" "quote" quote)
                                      (%cg-object "source" "source_1" "quote" "Mina"))))
    ((uiop:string-prefix-p "identity-page-" phase)
     (%cg-object "mentions" (map 'vector (lambda (id) (%cg-object "mention" id "status" "none" "candidates" #())) #("mention_1" "mention_2"))))
    ((equal phase "identity-resolve")
     (%cg-object "resolutions" (map 'vector (lambda (id) (%cg-object "mention" id "candidate" :null)) #("mention_1" "mention_2"))))
    ((equal phase "new-identity-groups")
     (%cg-object "groups"
       (if distinct
           (vector (%cg-object "mentions" #("mention_1") "source" "source_1" "quote" quote)
                   (%cg-object "mentions" (if overlap #("mention_1") #("mention_2")) "source" "source_1" "quote" quote))
           (vector (%cg-object "mentions" #("mention_1" "mention_2") "source" "source_1" "quote" (if unanchored "Invented evidence" quote))))))
    ((equal phase "new-identities")
     (let ((ids (gethash "eligible_mentions" (gethash "input" spec))))
       (assert (= (if distinct 2 1) (length ids)))
       (%cg-object "new_entities" (map 'vector (lambda (id)
         (let ((entity (%cg-detach (aref (gethash "new_entities" (sm-proposal)) 0))))
           (setf (gethash "mention" entity) id) entity)) ids))))
    ((equal phase "facts")
     (let* ((bindings (gethash "mention_bindings" (gethash "input" spec)))
            (handles (remove-duplicates (map 'list (lambda (b) (gethash "entity" b)) bindings) :test #'equal)))
       (assert (= (if distinct 2 1) (length handles)))
       (%cg-object "facts" (map 'vector (lambda (handle)
         (let ((fact (%cg-detach (aref (gethash "facts" (sm-proposal)) 0))))
           (setf (gethash "object" fact) handle (gethash "quote" (aref (gethash "evidence" fact) 0)) quote) fact)) handles)
         "name_corrections" #())))
    ((equal phase "review")
     (assert (gethash "new_identity_groups" (gethash "identity_comparison" (gethash "input" spec))))
     (gf-lab-model phase spec))
    (t (error "Unexpected phase ~a" phase))))

(dolist (distinct '(nil t))
  (let* ((*cgf-protocol* "identity-formation-v3")
         (ontology (gethash "ontology" (as-fixture))) (graph (make-context-graph ontology))
         (quote (if distinct "I own two different cats both named Mina."
                            "I own a cat named Mina. Mina is that same cat."))
         (episode (sm-episode "grouped-mentions" quote 100))
         (cache (make-hash-table :test #'equal)) (count 0) (pause t))
    (multiple-value-bind (full boundary) (lab-authority-context graph episode 0)
      (labels ((model (phase spec digest)
                 (let ((saved (gethash phase cache)))
                   (when saved (assert (equal digest (car saved))) (return-from model (%cg-detach (cdr saved)))))
                 (when (and pause (equal phase "new-identities")) (setf pause nil) (return-from model :paused-budget))
                 (incf count)
                 (let ((response (gg-model phase spec distinct quote)))
                   (setf (gethash phase cache) (cons digest response)) (%cg-detach response))))
        (assert (eq :paused-budget (%cgf-generate graph full 0 ontology "personal-context-core-glm53-v1.2" #'model)))
        (assert (= 4 count))
        (let* ((envelope (context-graph-runtime-read-json (context-graph-runtime-json
                          (%cgf-generate graph full 0 ontology "personal-context-core-glm53-v1.2" #'model))))
               (fresh (make-context-graph ontology)))
          (assert (= 7 count))
          (setf (gethash "episode_id" boundary) (gethash "episode_id" (gethash "context" envelope)))
          (%cgf-apply graph boundary full envelope)
          (%cgf-apply fresh boundary full envelope)
          (assert (= (if distinct 4 3) (context-graph-entity-count graph)))
          (assert (= (if distinct 2 1) (context-graph-fact-count graph)))
          (assert (%cg-authority-equal-p (%cg-authority-watermark graph "lab-agent" "lab-persona")
                                        (%cg-authority-watermark fresh "lab-agent" "lab-persona")))
          (assert (plusp (length (gethash "facts" (gethash "context" (%cg-authority-retrieve graph "lab-agent" "lab-persona" "Mina"))))))
          (assert (zerop (length (gethash "facts" (gethash "context" (%cg-authority-retrieve graph "lab-agent" "lab-persona" "asteroid")))))))))))

(dolist (bad '(:overlap :unanchored))
  (let* ((*cgf-protocol* "identity-formation-v3") (ontology (gethash "ontology" (as-fixture)))
         (graph (make-context-graph ontology)) (quote "I own a cat named Mina."))
    (multiple-value-bind (full boundary) (lab-authority-context graph (sm-episode "invalid-group" quote 100) 0)
      (declare (ignore boundary))
      (assert (sm-error (lambda () (%cgf-generate graph full 0 ontology "personal-context-core-glm53-v1.2"
        (lambda (phase spec digest) (declare (ignore digest))
          (gg-model phase spec (eq bad :overlap) quote :overlap (eq bad :overlap) :unanchored (eq bad :unanchored)))))
        (if (eq bad :overlap) "FORMATION_GROUP_OVERLAP" "FORMATION_GROUP_EVIDENCE_INVALID")))
      (assert (zerop (context-graph-entity-count graph))))))
(format t "MENTION-GROUPS repeated identity, distinct same-name identities, exact evidence, disjointness, pause and cold replay passed~%")
