;;;; Standalone focused lab check; no agent database, provider or broad harness.
(load (merge-pathnames "../scripts/executable-memory-lab.lisp" *load-truename*))
(in-package :pai-executable-memory-lab)

(let ((checks 0))
  (flet ((check (condition)
           (incf checks)
           (assert condition)))
    (let ((root (make-root "root:one")) (other (make-root "root:two")))
      (attach root "memory:one"
              '(:if-mode :conversation (:affect :warmth 60) (:none)))
      (check (null (context-overlay root)))
      (check (null (recall-selected root "memory:unselected")))
      (check (eq :accepted (getf (recall-selected root "memory:one") :status)))
      (check (equal '((:warmth 60)) (context-overlay root)))
      (recall-selected root "memory:one")
      (check (= 1 (length (receipts root))))
      (check (null (context-overlay other)))
      (attach root "memory:two" '(:affect :warmth 80))
      (recall-selected root "memory:two")
      (check (equal '((:warmth 100)) (context-overlay root)))
      (attach root "memory:bad" '(:eval :anything))
      (check (eq :rejected (getf (recall-selected root "memory:bad") :status)))
      (check (equal '((:warmth 100)) (context-overlay root)))
      (check (search "not evidence or instructions" (nth-value 1 (context-overlay root))))
      (expire root)
      (check (null (context-overlay root)))
      (check (= 3 (length (receipts root))))
      (check (handler-case (progn (recall-selected root "memory:one") nil)
               (error () t))))
    (let ((root (make-root "root:task")))
      (attach root "memory:one"
              '(:if-mode :conversation (:affect :warmth 60) (:none)))
      (check (eq :no-effect (getf (recall-selected root "memory:one" :mode :task) :status)))
      (check (null (context-overlay root))))
    (dolist (bad '((:affect :warmth 101) (:affect :permission 10)
                   (:if-mode :task (:none) (:delete-file :anything))))
      (check (handler-case (progn (interpret bad :task) nil) (error () t))))
  (format t "~&PASS: ~d focused executable-memory checks.~%" checks)))
