(in-package :agent)

(defun r0-bootstrap-parse-expected-row-count-lines (lines table-names)
  "Parse an exact TABLE<TAB>COUNT manifest for the stopped clone boundary."
  (let ((allowed (make-hash-table :test #'equal))
        (counts (make-hash-table :test #'equal)))
    (dolist (table table-names)
      (setf (gethash table allowed) t))
    (dolist (line lines)
      (let ((tab (position #\Tab line)))
        (unless (and tab
                     (plusp tab)
                     (= tab (position #\Tab line :from-end t)))
          (error "Malformed expected-row-count line"))
        (let ((table (subseq line 0 tab))
              (digits (subseq line (1+ tab))))
          (unless (gethash table allowed)
            (error "Unregistered expected-row-count table ~a" table))
          (when (nth-value 1 (gethash table counts))
            (error "Duplicate expected-row-count table ~a" table))
          (unless (and (plusp (length digits))
                       (every #'digit-char-p digits))
            (error "Invalid expected row count for ~a" table))
          (setf (gethash table counts) (parse-integer digits)))))
    (dolist (table table-names)
      (unless (nth-value 1 (gethash table counts))
        (error "Missing expected-row-count table ~a" table)))
    (unless (= (hash-table-count counts) (length table-names))
      (error "Expected-row-count manifest cardinality mismatch"))
    counts))

(defun r0-bootstrap-read-expected-row-counts (path table-names)
  (with-open-file (in path :direction :input)
    (r0-bootstrap-parse-expected-row-count-lines
     (loop for line = (read-line in nil nil)
           while line collect line)
     table-names)))

(defun r0-bootstrap-expected-row-total (counts table-names)
  (loop for table in table-names sum (gethash table counts)))

(defun r0-bootstrap-row-count-matches-p (counts table observed)
  (and (nth-value 1 (gethash table counts))
       (= observed (gethash table counts))))
