;;;; join.lisp -- fleet membership handshake (FLEET_DESIGN.md S2.4).
;;;;
;;;; The handshake is deliberately NOT authenticated by FLEET-HMAC-VERIFY --
;;;; there is no shared secret yet to sign with (that is the whole point of
;;;; this exchange). The security property instead comes from the numeric
;;;; code: it is generated by the requester, shown only on the requester's
;;;; own screen, and the approving operator must read it from there and
;;;; type it in -- binding the two OPERATORS, not just the two processes.
;;;; REQUEST-ID correlation is what stops an unsolicited JOIN-ACCEPT from
;;;; being silently applied (FLEET-JOIN-ACCEPT-APPLY only ever acts on a
;;;; request-id this agent itself generated and is still waiting on).
;;;;
;;;; This file is pure logic with no Hunchentoot dependency, like auth.lisp
;;;; and identity.lisp -- the HTTP/operator-command plumbing that calls into
;;;; it lives in the web adapter.
(in-package :pai.fleet)

(define-condition fleet-join-error (error)
  ((reason :initarg :reason :reader fleet-join-error-reason))
  (:report (lambda (condition stream)
             (format stream "Fleet join error: ~a"
                     (fleet-join-error-reason condition)))))

(defun fleet-join-code ()
  "A random 6-digit numeric code, as a zero-padded string. Drawn from
Ironclad's generator, not COMMON-LISP:RANDOM -- unlike FLEET-UUID4 this
code's whole security property depends on being unpredictable, since it is
the only thing standing between an approving operator and a forged join."
  (format nil "~6,'0d" (ironclad:strong-random 1000000)))

(defparameter +fleet-join-request-ttl-seconds+ 600
  "How long a pending join request (inbound or outbound) stays valid. Both
sides expire independently; a requester whose code goes stale before
approval must simply run /fleet-request again.")

;;; --- inbound: requests this agent has received, awaiting operator approval

(defstruct (fleet-join-request (:constructor %make-fleet-join-request))
  request-id requester-id requester-name requester-address code received-at)

(defstruct (fleet-inbound-join-store (:constructor %make-fleet-inbound-join-store))
  (requests (make-hash-table :test #'equal)))

(defun make-fleet-inbound-join-store () (%make-fleet-inbound-join-store))

(defun fleet-inbound-join-register
    (store &key request-id requester-id requester-name requester-address
                code (received-at (fleet-unix-time)))
  "Validate and store one inbound join request, keyed by REQUESTER-ID -- a
repeat request from the same requester replaces the pending entry (a fresh
code) rather than accumulating stale duplicates."
  (dolist (pair (list (cons "request-id" request-id)
                       (cons "requester-id" requester-id)
                       (cons "requester-name" requester-name)
                       (cons "requester-address" requester-address)
                       (cons "code" code)))
    (unless (and (stringp (cdr pair)) (plusp (length (cdr pair))))
      (error "fleet-inbound-join-register requires a non-empty ~a" (car pair))))
  (unless (integerp received-at)
    (error "fleet-inbound-join-register requires an integer received-at"))
  (setf (gethash requester-id (fleet-inbound-join-store-requests store))
        (%make-fleet-join-request
         :request-id request-id :requester-id requester-id
         :requester-name requester-name :requester-address requester-address
         :code code :received-at received-at)))

(defun %fleet-join-request-expired-p (request now)
  (> (- now (fleet-join-request-received-at request))
     +fleet-join-request-ttl-seconds+))

(defun fleet-inbound-join-find (store requester-id &key (now (fleet-unix-time)))
  "The pending request from REQUESTER-ID, or NIL if there is none or it has
expired. Does not remove an expired entry -- see FLEET-INBOUND-JOIN-PRUNE."
  (let ((request (gethash requester-id (fleet-inbound-join-store-requests store))))
    (and request (not (%fleet-join-request-expired-p request now)) request)))

(defun fleet-inbound-join-remove (store requester-id)
  (remhash requester-id (fleet-inbound-join-store-requests store)))

(defun fleet-inbound-join-prune (store &key (now (fleet-unix-time)))
  "Remove every expired inbound request. Returns the still-pending requests,
oldest first, so a caller (e.g. an operator '/fleet pending' listing) gets
a clean, current view in one call."
  (let ((table (fleet-inbound-join-store-requests store)))
    (loop for requester-id being the hash-keys of table using (hash-value request)
          when (%fleet-join-request-expired-p request now)
            collect requester-id into stale
          finally (dolist (id stale) (remhash id table)))
    (sort (loop for request being the hash-values of table collect request)
          #'< :key #'fleet-join-request-received-at)))

;;; --- outbound: requests this agent has sent, awaiting a join-accept

(defstruct (fleet-outbound-join-request (:constructor %make-fleet-outbound-join-request))
  request-id target-address code sent-at)

(defstruct (fleet-outbound-join-store (:constructor %make-fleet-outbound-join-store))
  (requests (make-hash-table :test #'equal)))

(defun make-fleet-outbound-join-store () (%make-fleet-outbound-join-store))

(defun fleet-outbound-join-register
    (store &key request-id target-address code (sent-at (fleet-unix-time)))
  (dolist (pair (list (cons "request-id" request-id)
                       (cons "target-address" target-address)
                       (cons "code" code)))
    (unless (and (stringp (cdr pair)) (plusp (length (cdr pair))))
      (error "fleet-outbound-join-register requires a non-empty ~a" (car pair))))
  (unless (integerp sent-at)
    (error "fleet-outbound-join-register requires an integer sent-at"))
  (setf (gethash request-id (fleet-outbound-join-store-requests store))
        (%make-fleet-outbound-join-request
         :request-id request-id :target-address target-address
         :code code :sent-at sent-at)))

(defun fleet-outbound-join-find (store request-id &key (now (fleet-unix-time)))
  (let ((request (gethash request-id (fleet-outbound-join-store-requests store))))
    (and request
         (<= (- now (fleet-outbound-join-request-sent-at request))
             +fleet-join-request-ttl-seconds+)
         request)))

(defun fleet-outbound-join-remove (store request-id)
  (remhash request-id (fleet-outbound-join-store-requests store)))

(defun fleet-outbound-join-prune (store &key (now (fleet-unix-time)))
  (let ((table (fleet-outbound-join-store-requests store)))
    (loop for request-id being the hash-keys of table using (hash-value request)
          when (> (- now (fleet-outbound-join-request-sent-at request))
                  +fleet-join-request-ttl-seconds+)
            collect request-id into stale
          finally (dolist (id stale) (remhash id table)))
    (sort (loop for request being the hash-values of table collect request)
          #'< :key #'fleet-outbound-join-request-sent-at)))

;;; --- approval and acceptance ----------------------------------------------

(defun fleet-join-approve
    (inbound-store fleet-store requester-id typed-code
     &key own-id own-name own-address (now (fleet-unix-time)))
  "The approving operator's action: verify TYPED-CODE against the pending
request from REQUESTER-ID, and on a match, mint a fresh shared secret,
persist the new peer, and return (VALUES PEER JOIN-ACCEPT-PLIST) -- the
plist is ready for the HTTP layer to serialize and POST back as
/fleet/join-accept. Signals FLEET-JOIN-ERROR (not a plain error) for every
rejection reason, so the HTTP layer can report a specific, honest cause
without leaking whether a wrong code was close."
  (unless (and (stringp own-id) (plusp (length own-id))
               (stringp own-name) (plusp (length own-name))
               (stringp own-address) (plusp (length own-address)))
    (error "fleet-join-approve requires non-empty own-id, own-name and own-address"))
  (when (equal requester-id own-id)
    (error 'fleet-join-error :reason "cannot join self"))
  (let ((request (fleet-inbound-join-find inbound-store requester-id :now now)))
    (unless request
      (error 'fleet-join-error :reason "no pending request from this peer (or it expired)"))
    (unless (string= typed-code (fleet-join-request-code request))
      (error 'fleet-join-error :reason "code does not match"))
    (let* ((secret (fleet-shared-secret))
           (peer (make-fleet-peer
                  :id requester-id
                  :name (fleet-join-request-requester-name request)
                  :address (fleet-join-request-requester-address request)
                  :shared-secret secret
                  :joined-at (get-universal-time))))
      (fleet-store-add-peer fleet-store peer)
      (fleet-inbound-join-remove inbound-store requester-id)
      (values peer
              (list :request-id (fleet-join-request-request-id request)
                    :acceptor-id own-id
                    :acceptor-name own-name
                    :acceptor-address own-address
                    :shared-secret (ironclad:byte-array-to-hex-string secret))))))

(defun fleet-join-accept-apply
    (outbound-store fleet-store request-id
     &key acceptor-id acceptor-name acceptor-address shared-secret-hex
          (now (fleet-unix-time)))
  "Apply an incoming /fleet/join-accept: only ever acts on a REQUEST-ID this
agent itself generated and is still waiting on (FLEET-OUTBOUND-JOIN-FIND) --
an unsolicited or stale request-id is refused, not silently accepted, since
that correlation is this side's entire defense against a forged accept."
  (let ((request (fleet-outbound-join-find outbound-store request-id :now now)))
    (unless request
      (error 'fleet-join-error
             :reason "join-accept does not correlate to any pending request"))
    (let* ((secret (ironclad:hex-string-to-byte-array shared-secret-hex))
           (peer (make-fleet-peer
                  :id acceptor-id :name acceptor-name :address acceptor-address
                  :shared-secret secret :joined-at (get-universal-time))))
      (fleet-store-add-peer fleet-store peer)
      (fleet-outbound-join-remove outbound-store request-id)
      peer)))
