;;;; Pure policy foundation. Runtime adapters authenticate and resolve snapshots.
;;;; No IO, implicit owner grants, model judgments, clocks, or cached permissions.
(in-package :pai.memory-access)

(define-condition memory-access-input-error (error) ()
  (:report (lambda (condition stream)
             (declare (ignore condition)) (write-string "Invalid memory access envelope" stream))))

(defun %ma-require (value)
  (unless value (error 'memory-access-input-error)) value)
(defun %ma-object (&rest pairs)
  (let ((object (make-hash-table :test #'equal)))
    (loop for (key value) on pairs by #'cddr do (setf (gethash (copy-seq key) object) value)) object))
(defun %ma-detach (value)
  (cond ((hash-table-p value)
         (let ((result (make-hash-table :test #'equal)))
           (maphash (lambda (k v) (setf (gethash (copy-seq k) result) (%ma-detach v))) value)
           result))
        ((stringp value) (copy-seq value))
        ((vectorp value) (map 'vector #'%ma-detach value))
        (t value)))
(defun %ma-keys (object keys)
  (and (hash-table-p object) (= (length keys) (hash-table-count object))
       (every (lambda (key) (nth-value 1 (gethash key object))) keys)))
(defun %ma-string (value &optional (maximum 180))
  (and (stringp value) (<= 1 (length value) maximum)
       (find-if (lambda (ch) (not (find ch '(#\Space #\Tab #\Newline #\Return)))) value)))
(defun %ma-nullable (value) (or (eq value :null) (%ma-string value)))
(defun %ma-enum (value options) (and (stringp value) (member value options :test #'string=)))
(defun %ma-boolean (value) (member value '(:true :false)))
(defun %ma-array (value maximum &optional (minimum 0))
  (and (vectorp value) (not (stringp value)) (<= minimum (length value) maximum)))
(defun %ma-strings (value maximum &optional (minimum 0))
  (and (%ma-array value maximum minimum) (every #'%ma-string value)
       (= (length value) (length (remove-duplicates value :test #'equal)))))
(defun %ma-natural (value) (and (integerp value) (<= 0 value)))

(defun memory-access-canonical-json (value)
  "Canonical integer-only JSON; booleans/null have distinct explicit sentinels."
  (with-output-to-string (out)
    (labels ((emit (x)
               (cond
                 ((hash-table-p x)
                  (%ma-require (loop for k being the hash-keys of x always (stringp k)))
                  (write-char #\{ out)
                  (loop for k in (sort (loop for k being the hash-keys of x collect k) #'string<)
                        for first = t then nil
                        do (unless first (write-char #\, out))
                           (write-string (shasht:write-json k nil) out)
                           (write-char #\: out) (emit (gethash k x)))
                  (write-char #\} out))
                 ((stringp x) (write-string (shasht:write-json x nil) out))
                 ((vectorp x)
                  (write-char #\[ out)
                  (loop for item across x for first = t then nil
                        do (unless first (write-char #\, out)) (emit item))
                  (write-char #\] out))
                 ((integerp x) (format out "~d" x))
                 ((eq x :null) (write-string "null" out))
                 ((eq x :true) (write-string "true" out))
                 ((eq x :false) (write-string "false" out))
                 (t (%ma-require nil)))))
      (emit value))))
(defun %ma-digest (value)
  (string-downcase (ironclad:byte-array-to-hex-string
                    (ironclad:digest-sequence
                     :sha256 (sb-ext:string-to-octets (memory-access-canonical-json value)
                                                        :external-format :utf-8)))))
(defun %ma-equal (a b) (equal (memory-access-canonical-json a) (memory-access-canonical-json b)))
(defun %ma-member (item rows) (find item rows :test #'%ma-equal))
(defun %ma-partition (value)
  (and (%ma-keys value '("agent_id" "persona_id"))
       (%ma-string (gethash "agent_id" value))
       (%ma-nullable (gethash "persona_id" value))))
(defun %ma-resource (value)
  (and (%ma-keys value '("store" "resource_id" "version_id" "component"))
       (%ma-enum (gethash "store" value) '("event" "episodic" "semantic" "graph" "artifact" "cache"))
       (%ma-enum (gethash "component" value) '("content" "descriptor" "claim" "evidence" "lineage" "embedding"))
       (%ma-string (gethash "resource_id" value)) (%ma-string (gethash "version_id" value))))
(defun %ma-policy-ref (value)
  (and (%ma-keys value '("policy_id" "policy_version"))
       (%ma-string (gethash "policy_id" value)) (%ma-string (gethash "policy_version" value))))
(defun %ma-records (value maximum predicate &optional (minimum 0))
  (and (%ma-array value maximum minimum) (every predicate value)
       (= (length value) (length (remove-duplicates value :test #'%ma-equal)))))
(defun %ma-sensitivity (value)
  (position value '("public" "personal" "sensitive" "restricted") :test #'equal))

(defun %ma-protection (value)
  (and (%ma-keys value '("schema_version" "resource_ref" "partition" "controller_principal_ids"
                         "subject_principal_ids" "sensitivity" "categories" "policy_refs"
                         "dependency_refs" "lineage_complete" "protection_revision"))
       (eql 1 (gethash "schema_version" value))
       (equal "memory-protection-v1" (gethash "protection_revision" value))
       (%ma-resource (gethash "resource_ref" value)) (%ma-partition (gethash "partition" value))
       (%ma-strings (gethash "controller_principal_ids" value) 8 1)
       (%ma-strings (gethash "subject_principal_ids" value) 16)
       (%ma-sensitivity (gethash "sensitivity" value))
       (%ma-strings (gethash "categories" value) 16 1)
       (%ma-records (gethash "policy_refs" value) 16 #'%ma-policy-ref 1)
       (%ma-records (gethash "dependency_refs" value) 64 #'%ma-resource)
       (%ma-boolean (gethash "lineage_complete" value))))
(defun memory-access-validate-protection (protection)
  (%ma-require (%ma-protection protection)) (%ma-object "valid" :true))

(defun %ma-context (value)
  (and (%ma-keys value '("schema_version" "executor_principal_id" "authority_principal_id"
                         "recipient_principal_id" "recipient_binding_id" "recipient_set_digest"
                         "task_id" "purpose" "channel_id" "partition" "action" "grant_ids"
                         "now_utc" "policy_epoch"))
       (eql 1 (gethash "schema_version" value))
       (every (lambda (key) (%ma-string (gethash key value)))
              '("executor_principal_id" "authority_principal_id" "purpose" "channel_id"))
       (every (lambda (key) (%ma-nullable (gethash key value)))
              '("recipient_principal_id" "recipient_binding_id" "recipient_set_digest" "task_id"))
       (%ma-partition (gethash "partition" value))
       (%ma-enum (gethash "action" value) '("read" "derive" "disclose" "delegate"))
       (%ma-strings (gethash "grant_ids" value) 8)
       (%ma-natural (gethash "now_utc" value)) (%ma-natural (gethash "policy_epoch" value))))
(defun %ma-principal (value)
  (and (%ma-keys value '("principal_id" "kind" "identity_binding_id" "status"))
       (%ma-string (gethash "principal_id" value)) (%ma-string (gethash "identity_binding_id" value))
       (%ma-enum (gethash "kind" value) '("human" "agent" "service"))
       (%ma-enum (gethash "status" value) '("verified" "unverified" "revoked"))))

(defun memory-access-validate-context (context)
  "Shape validation only; a context is not a policy decision or permission."
  (%ma-require (%ma-context context)) (%ma-object "valid" :true))
(defun %ma-selector (value)
  (and (%ma-keys value '("partition" "resource_refs" "categories" "maximum_sensitivity"))
       (%ma-partition (gethash "partition" value))
       (%ma-records (gethash "resource_refs" value) 64 #'%ma-resource)
       (%ma-strings (gethash "categories" value) 16)
       (plusp (+ (length (gethash "resource_refs" value)) (length (gethash "categories" value))))
       (%ma-sensitivity (gethash "maximum_sensitivity" value))))
(defun %ma-rule (value)
  (and (%ma-keys value '("rule_id" "policy_id" "policy_version" "effect" "executor_principal_ids"
                         "recipient_principal_ids" "actions" "purposes" "channels"
                         "allowed_components" "resource_selectors" "require_task_grant"))
       (every (lambda (key) (%ma-string (gethash key value))) '("rule_id" "policy_id" "policy_version"))
       (%ma-enum (gethash "effect" value) '("allow" "deny"))
       (%ma-strings (gethash "executor_principal_ids" value) 16 1)
       (%ma-strings (gethash "recipient_principal_ids" value) 16)
       (%ma-strings (gethash "actions" value) 4 1)
       (every (lambda (action) (%ma-enum action '("read" "derive" "disclose" "delegate")))
              (gethash "actions" value))
       (%ma-strings (gethash "purposes" value) 16 1) (%ma-strings (gethash "channels" value) 16 1)
       (%ma-strings (gethash "allowed_components" value) 6 1)
       (every (lambda (component) (%ma-enum component '("content" "descriptor" "claim" "evidence" "lineage" "embedding")))
              (gethash "allowed_components" value))
       (%ma-records (gethash "resource_selectors" value) 16 #'%ma-selector 1)
       (%ma-boolean (gethash "require_task_grant" value))))

(defun %ma-closure (ref context protections)
  "Resolve complete dependency closure; cycles and hidden ancestors fail closed."
  (let ((seen (make-hash-table :test #'equal)) (active (make-hash-table :test #'equal)) (rows nil))
    (block resolve
      (labels ((visit (item depth)
                 (when (> depth 16) (return-from resolve (values nil "ACCESS_INCOMPLETE")))
                 (let ((key (memory-access-canonical-json item)))
                   (when (gethash key active) (return-from resolve (values nil "ACCESS_INCOMPLETE")))
                   (unless (gethash key seen)
                     (let ((row (find item protections :key (lambda (p) (gethash "resource_ref" p))
                                                     :test #'%ma-equal)))
                       (unless row (return-from resolve (values nil "PROTECTION_MISSING")))
                       (unless (%ma-equal (gethash "partition" context) (gethash "partition" row))
                         (return-from resolve (values nil "PARTITION_DENIED")))
                       (unless (eq :true (gethash "lineage_complete" row))
                         (return-from resolve (values nil "ACCESS_INCOMPLETE")))
                       (setf (gethash key active) t)
                       (loop for dependency across (gethash "dependency_refs" row) do (visit dependency (1+ depth)))
                       (remhash key active) (setf (gethash key seen) t) (push row rows))))))
        (visit ref 0)
        (values rows nil)))))

(defun %ma-rule-matches (rule ref context protection categories sensitivity)
  (and (find (gethash "executor_principal_id" context) (gethash "executor_principal_ids" rule) :test #'equal)
       (let ((recipient (gethash "recipient_principal_id" context))
             (allowed (gethash "recipient_principal_ids" rule)))
         (if (eq recipient :null)
             (and (zerop (length allowed))
                  (%ma-enum (gethash "action" context) '("read" "derive")))
             (find recipient allowed :test #'equal)))
       (loop for (key array) in '(("action" "actions") ("purpose" "purposes")
                                 ("channel_id" "channels"))
             always (find (gethash key context) (gethash array rule) :test #'equal))
       (find (gethash "component" ref) (gethash "allowed_components" rule) :test #'equal)
       (some (lambda (selector)
               (and (%ma-equal (gethash "partition" protection) (gethash "partition" selector))
                    (or (zerop (length (gethash "resource_refs" selector)))
                        (%ma-member ref (gethash "resource_refs" selector)))
                    (let ((selected (gethash "categories" selector)))
                      (or (zerop (length selected))
                          (if (equal "deny" (gethash "effect" rule))
                              (some (lambda (c) (find c selected :test #'equal)) categories)
                              (every (lambda (c) (find c selected :test #'equal)) categories))))
                    (<= sensitivity (%ma-sensitivity (gethash "maximum_sensitivity" selector)))))
             (gethash "resource_selectors" rule))))

(defun memory-access-decide (resource-ref access-context policy-snapshot)
  "Evaluate internal resource use. Grant-dependent uses fail closed in this slice.
This is a foundation API, not a claim of memory-wide enforcement. Disclosure,
delegation and grant-required reads remain denied until grant qualification."
  (%ma-require (and (%ma-resource resource-ref) (%ma-context access-context)))
  (let ((matched nil))
    (labels ((decision (outcome code)
               (%ma-detach
                (%ma-object "outcome" outcome "reason_code" code "resource_ref" resource-ref
                            "action" (gethash "action" access-context)
                            "context_digest" (%ma-digest access-context)
                            "policy_epoch" (gethash "policy_epoch" access-context)
                            "matched_rule_ids" (coerce (subseq (sort (remove-duplicates matched :test #'equal) #'string<)
                                                              0 (min 64 (length (remove-duplicates matched :test #'equal)))) 'vector)))))
      (unless (hash-table-p policy-snapshot)
        (return-from memory-access-decide (decision "deny" "POLICY_UNAVAILABLE")))
      (%ma-require (%ma-keys policy-snapshot '("schema_version" "policy_revision" "epoch" "principals"
                                              "protections" "rules" "tasks" "grants" "recipes"
                                              "recipe_authorizations" "revoked_grant_ids")))
      (unless (and (eql 1 (gethash "schema_version" policy-snapshot))
                   (equal "memory-access-policy-v1" (gethash "policy_revision" policy-snapshot))
                   (eql (gethash "policy_epoch" access-context) (gethash "epoch" policy-snapshot)))
        (return-from memory-access-decide (decision "deny" "POLICY_UNAVAILABLE")))
      (loop for (key maximum) in '(("principals" 64) ("protections" 256) ("rules" 512)
                                  ("tasks" 32) ("grants" 32) ("recipes" 16)
                                  ("recipe_authorizations" 64) ("revoked_grant_ids" 32))
            do (unless (%ma-array (gethash key policy-snapshot) maximum)
                 (return-from memory-access-decide (decision "deny" "ACCESS_INCOMPLETE"))))
      (%ma-require (and (every #'%ma-principal (gethash "principals" policy-snapshot))
                       (every #'%ma-protection (gethash "protections" policy-snapshot))
                       (every #'%ma-rule (gethash "rules" policy-snapshot))))
      ;; Reject ambiguous runtime registries, even if one duplicate would allow.
      (loop for (key id) in '(("principals" "principal_id") ("protections" "resource_ref") ("rules" "rule_id"))
            for rows = (gethash key policy-snapshot)
            do (%ma-require (= (length rows)
                               (length (remove-duplicates rows :key (lambda (row) (gethash id row)) :test #'%ma-equal)))))
      (dolist (key '("executor_principal_id" "authority_principal_id" "recipient_principal_id"))
        (let ((id (gethash key access-context)))
          (unless (eq id :null)
            (let ((principal (find id (gethash "principals" policy-snapshot)
                                  :key (lambda (p) (gethash "principal_id" p)) :test #'equal)))
              (unless (and principal (equal "verified" (gethash "status" principal)))
                (return-from memory-access-decide (decision "deny" "IDENTITY_UNVERIFIED")))))))
      (unless (eq :null (gethash "recipient_principal_id" access-context))
        ;; External contexts need task/binding/grant enforcement; never treat
        ;; verified directory membership as authority to disclose.
        (return-from memory-access-decide (decision "deny" "GRANT_INVALID")))
      (unless (and (eq :null (gethash "recipient_binding_id" access-context))
                   (eq :null (gethash "recipient_set_digest" access-context)))
        (return-from memory-access-decide (decision "deny" "RECIPIENT_CHANGED")))
      (multiple-value-bind (closure failure)
          (%ma-closure resource-ref access-context (gethash "protections" policy-snapshot))
        (when failure (return-from memory-access-decide (decision "deny" failure)))
        (let* ((categories (remove-duplicates (loop for p in closure append (coerce (gethash "categories" p) 'list)) :test #'equal))
               (sensitivity (apply #'max (mapcar (lambda (p) (%ma-sensitivity (gethash "sensitivity" p))) closure)))
               (policies (remove-duplicates (loop for p in closure append (coerce (gethash "policy_refs" p) 'list)) :test #'%ma-equal))
               (allowed (make-hash-table :test #'equal)) (denied nil) (work 0))
          (dolist (policy policies)
            (loop for rule across (gethash "rules" policy-snapshot)
                  do (when (> (incf work) 16384)
                       (return-from memory-access-decide (decision "deny" "ACCESS_INCOMPLETE")))
                  when (and (equal (gethash "policy_id" policy) (gethash "policy_id" rule))
                            (equal (gethash "policy_version" policy) (gethash "policy_version" rule))
                            (%ma-rule-matches rule resource-ref access-context (first closure) categories sensitivity))
                    do (push (gethash "rule_id" rule) matched)
                       (if (equal "deny" (gethash "effect" rule)) (setf denied t)
                           (unless (eq :true (gethash "require_task_grant" rule))
                             (setf (gethash (memory-access-canonical-json policy) allowed) t)))))
          (when denied (return-from memory-access-decide (decision "deny" "EXPLICIT_DENY")))
          (unless (every (lambda (p) (gethash (memory-access-canonical-json p) allowed)) policies)
            (return-from memory-access-decide (decision "deny" "ALLOW_MISSING")))
          (when (or (%ma-enum (gethash "action" access-context) '("disclose" "delegate"))
                    (not (eq :null (gethash "task_id" access-context)))
                    (plusp (length (gethash "grant_ids" access-context))))
            (return-from memory-access-decide (decision "deny" "GRANT_INVALID")))
          (decision "allow" "POLICY_SATISFIED"))))))

(defun memory-access-derive-protection (output-ref input-refs access-context policy-snapshot)
  "Inherit all effective input restrictions. Never declassify derived data.
The runtime supplies every influencing input, including model context. This
function does not trust an extractor to identify a smaller influence set."
  (%ma-require (and (%ma-resource output-ref) (%ma-records input-refs 64 #'%ma-resource 1)
                   (%ma-context access-context)))
  (labels ((result (outcome code &optional value)
             (%ma-detach (%ma-object "outcome" outcome "reason_code" code "value" (or value :null))))
           (deny (code) (return-from memory-access-derive-protection (result "deny" code)))
           (strings (rows key)
             (coerce (sort (remove-duplicates (loop for row in rows append (coerce (gethash key row) 'list)) :test #'equal) #'string<) 'vector)))
    (unless (equal "derive" (gethash "action" access-context)) (deny "ALLOW_MISSING"))
    (when (%ma-member output-ref input-refs) (deny "PAYLOAD_INVALID"))
    (let ((all nil))
      (loop for ref across input-refs
            do (let ((decision (memory-access-decide ref access-context policy-snapshot)))
                 (unless (equal "allow" (gethash "outcome" decision)) (deny (gethash "reason_code" decision))))
               (multiple-value-bind (closure failure) (%ma-closure ref access-context (gethash "protections" policy-snapshot))
                 (when failure (deny failure))
                 (dolist (row closure) (pushnew row all :test #'%ma-equal))))
      ;; A dependency cycle through an existing output is not a fresh resource.
      (when (find output-ref all :test #'%ma-equal :key (lambda (p) (gethash "resource_ref" p))) (deny "PAYLOAD_INVALID"))
      (let* ((controllers (strings all "controller_principal_ids")) (subjects (strings all "subject_principal_ids"))
             (categories (strings all "categories"))
             (policies (coerce (sort (remove-duplicates (loop for p in all append (coerce (gethash "policy_refs" p) 'list)) :test #'%ma-equal)
                                     #'string< :key #'memory-access-canonical-json) 'vector))
             (sensitivity (apply #'max (mapcar (lambda (p) (%ma-sensitivity (gethash "sensitivity" p))) all)))
             (protection (%ma-object "schema_version" 1 "resource_ref" output-ref "partition" (gethash "partition" access-context)
                                     "controller_principal_ids" controllers "subject_principal_ids" subjects
                                     "sensitivity" (nth sensitivity '("public" "personal" "sensitive" "restricted"))
                                     "categories" categories "policy_refs" policies
                                     "dependency_refs" (sort (copy-seq input-refs) #'string< :key #'memory-access-canonical-json)
                                     "lineage_complete" :true "protection_revision" "memory-protection-v1")))
        ;; Bounds produce incompleteness, not truncation or eviction of a policy.
        (unless (%ma-protection protection) (deny "ACCESS_INCOMPLETE"))
        (let ((existing (find output-ref (gethash "protections" policy-snapshot) :test #'%ma-equal :key (lambda (p) (gethash "resource_ref" p)))))
          (when (and existing (not (%ma-equal existing protection))) (deny "PAYLOAD_INVALID")))
        (result "allow" "POLICY_SATISFIED" protection)))))
