;;;; Bounded, agent-scoped reads of original event-ledger evidence.
(in-package :agent)

(defun %recursive-experience-arguments (arguments)
  (unless (hash-table-p arguments)
    (error "search-experience requires an object"))
  (when (nth-value 1 (gethash "event_id" arguments))
    (unless (and (every (lambda (key) (member key '("event_id" "offset") :test #'equal))
                        (%recursive-object-keys arguments))
                 (typep (gethash "event_id" arguments) '(integer 1 *))
                 (typep (gethash "offset" arguments 0) '(integer 0 33554432)))
      (error "Exact experience reads accept only positive event_id and optional nonnegative offset"))
    (return-from %recursive-experience-arguments arguments))
  (unless (and (every (lambda (key)
                        (member key '("query" "hours" "from_unix" "to_unix"
                                      "cursor" "limit") :test #'equal))
                      (%recursive-object-keys arguments))
               (stringp (gethash "query" arguments ""))
               (<= (length (gethash "query" arguments "")) 200)
               (typep (gethash "hours" arguments 24) '(integer 1 8760))
               (typep (gethash "limit" arguments 10) '(integer 1 20))
               (every (lambda (key)
                        (or (not (nth-value 1 (gethash key arguments)))
                            (typep (gethash key arguments) '(integer 0 4102444800))))
                      '("from_unix" "to_unix"))
               (let ((cursor (gethash "cursor" arguments)))
                 (or (null cursor)
                     (and (stringp cursor) (<= 1 (length cursor) 128)))))
    (error "Invalid search-experience arguments"))
  arguments)

(defun %recursive-experience-evidence-page (arguments)
  "Return a page of original conversation/tool evidence, without private reasoning."
  (unless (and *event-authority-port*
               (functionp (getf *event-authority-port* :read-event)))
    (error "Exact evidence requires an installed indexed event authority"))
  (let* ((id (gethash "event_id" arguments))
         (event (loop for kind in '("user-message" "agent-message" "model-response"
                                     "recursive-tool-result")
                      for candidate = (event-read-event id :event-type kind)
                      when candidate return candidate))
         (kind (and event (gethash "type" event)))
         (payload (and event (gethash "payload" event)))
         (offset (gethash "offset" arguments 0)))
    (unless (and event (equal *conscious-recursive-mind-agent-id*
                              (gethash "agent_id" event))
                 (hash-table-p payload))
      (error "Event is absent or not readable evidence for this agent"))
    (let* ((body
             (cond
               ((equal kind "model-response")
                (let ((message (gethash "assistant_message" payload)))
                  (unless (and (equal "accepted" (gethash "status" payload))
                               (hash-table-p message))
                    (error "Event has no accepted native assistant evidence"))
                  (obj "content" (gethash "content" message :null)
                       "tool_calls"
                       (coerce (loop for call in (%recursive-items
                                                  (let ((calls (gethash "tool_calls" message)))
                                                    (unless (eq calls :null) calls)))
                                     for fn = (gethash "function" call)
                                     collect (obj "id" (gethash "id" call)
                                                  "name" (gethash "name" fn)
                                                  "arguments" (gethash "arguments" fn)))
                               'vector))))
               ((equal kind "recursive-tool-result")
                (obj "tool_name" (gethash "tool_name" payload)
                     "tool_call_id" (gethash "tool_call_id" payload)
                     "execution_status" (gethash "execution_status" payload)
                     "process_outcome" (gethash "process_outcome" payload :null)
                     "content" (gethash "content" payload)))
               (t (obj "text" (gethash "text" payload)))))
           (text (shasht:write-json body nil))
           (end (min (length text) (+ offset 4000))))
      (when (> offset (length text))
        (error "Evidence offset exceeds the original content length"))
      (obj "source_event_id" id "event_type" kind
           "caused_by" (gethash "caused_by" event :null)
           "format" "paged-json-evidence-without-provider-reasoning"
           "offset" offset "next_offset" (if (< end (length text)) end :null)
           "total_characters" (length text) "content" (subseq text offset end)))))

(defun %recursive-search-experience (arguments)
  (%recursive-experience-arguments arguments)
  (when (gethash "event_id" arguments)
    (return-from %recursive-search-experience
      (shasht:write-json (%recursive-experience-evidence-page arguments) nil)))
  (let* ((query (gethash "query" arguments ""))
         (cursor (gethash "cursor" arguments))
         (parts (and cursor (uiop:split-string cursor :separator ":")))
         (now (- (get-universal-time) 2208988800))
         (to (gethash "to_unix" arguments now))
         (from (gethash "from_unix" arguments
                        (max 0 (- to (* 3600 (gethash "hours" arguments 24))))))
         (before nil)
         (limit (gethash "limit" arguments 10)))
    (when cursor
      (unless (and (= 3 (length parts))
                   (every (lambda (part)
                            (and (plusp (length part))
                                 (every #'digit-char-p part))) parts))
        (error "Invalid experience cursor"))
      (setf from (parse-integer (first parts))
            to (parse-integer (second parts))
            before (parse-integer (third parts))))
    (unless (and (<= 0 from to 4102444800)
                 (or (null before) (<= 1 before most-positive-fixnum)))
      (error "Invalid experience time window"))
    (multiple-value-bind (events next)
        (event-experience-page (+ from 2208988800) (+ to 2208988800)
                               before limit)
      (let ((rows nil))
        (dolist (event events)
          (let* ((payload (gethash "payload" event))
                 (text (format nil "~{~a~^~%~}"
                               (loop for key in '("text" "content" "question" "finding"
                                                 "summary" "reason" "disposition"
                                                 "tool_name" "boundary_outcome"
                                                 "sender_name" "sender_id")
                                     for value = (gethash key payload)
                                     when (stringp value) collect value))))
            (when (or (zerop (length query)) (search query text :test #'char-equal))
              (push (obj "source_id" (gethash "id" event)
                         "event_type" (gethash "type" event)
                         "recorded_at" (gethash "timestamp" event)
                         "agent_id" (gethash "agent_id" event)
                         "sender_id" (gethash "sender_id" payload :null)
                         "thread_id" (gethash "thread_id" payload :null)
                         "caused_by" (gethash "caused_by" event :null)
                         "excerpt" (subseq text 0 (min 400 (length text)))
                         "excerpt_truncated" (> (length text) 400)) rows))))
        (shasht:write-json
         (obj "from_unix" from "to_unix" to "order" "newest recorded first"
              "coverage" "Selected agent-scoped ledger evidence. Text matching is literal within each page; an empty filtered page does not establish absence."
              "scanned" (length events) "results" (coerce (nreverse rows) 'vector)
              "next_cursor" (if next (format nil "~d:~d:~d" from to next) :null))
         nil)))))
