;;;; Pure working-context projection. Loading defines; it never reads or writes.
(in-package :agent)

(defun %sac-copy (value)
  (shasht:read-json (shasht:write-json value nil)))

(defun %sac-array-list (value)
  (cond ((and (vectorp value) (not (stringp value))) (coerce value 'list))
        ((listp value) value)
        (t (error "Activity membership must be an array"))))

(defun %sac-root-exchange (root events)
  "Project one root without provider reasoning or invented execution results."
  (let ((messages nil) (evidence nil) (outcomes nil) (pending nil)
        (seen-calls (make-hash-table :test #'equal)) (started nil) (finished nil))
    (dolist (event events)
      (let* ((id (gethash "id" event)) (type (gethash "type" event))
             (p (gethash "payload" event)))
        (cond
          ((eql id root)
           (unless (and (equal type "user-message") (hash-table-p p)
                        (stringp (gethash "text" p)) (not started))
             (error "Activity root is not an exact user exchange"))
           (setf started t)
           (push (obj "role" "user" "content" (gethash "text" p)) messages)
           (push id evidence))
          ((member type '("model-response" "recursive-tool-result" "agent-message"
                          "recursive-root-failed") :test #'equal)
           (unless (and started (not finished) (hash-table-p p))
             (error "Activity exchange evidence is out of order"))
           (cond
             ((equal type "recursive-root-failed")
              ;; A context-open failure is a terminal, no-send disposition for
              ;; this exact root.  Preserve the user message and receipt as
              ;; evidence, but do not manufacture an assistant reply.
              (unless (and (null pending)
                           (equal "context-open" (gethash "stage" p))
                           (equal "recursive-context-open-failed"
                                  (gethash "error_code" p)))
                (error "Activity root failure is malformed or out of order"))
              (push id evidence)
              (setf finished t))
             ((and (equal type "model-response") (equal "accepted" (gethash "status" p)))
              (when pending (error "Activity model response precedes pending tool outcomes"))
              (let* ((message (gethash "assistant_message" p))
                     (raw-calls (and (hash-table-p message) (gethash "tool_calls" message)))
                     (calls (and raw-calls (not (eq raw-calls :null)) (%sac-array-list raw-calls)))
                     (model-id (gethash "model_call_id" p)))
                (unless (hash-table-p message)
                  (error "Activity requires original accepted response, not hot-cache compaction"))
                (when calls
                  (unless (stringp model-id) (error "Activity tool batch lacks model identity"))
                  (let ((clean nil))
                    (dolist (call calls)
                      (let* ((call-id (gethash "id" call)) (fn (gethash "function" call))
                             (key (list model-id call-id)))
                        (unless (and (stringp call-id) (plusp (length call-id))
                                     (hash-table-p fn) (stringp (gethash "name" fn))
                                     (stringp (gethash "arguments" fn))
                                     (not (gethash key seen-calls)))
                          (error "Activity tool call is malformed or duplicated"))
                        (setf (gethash key seen-calls) t)
                        (push (list key (gethash "name" fn)) pending)
                        (push (obj "id" call-id "type" "function"
                                   "function" (obj "name" (gethash "name" fn)
                                                   "arguments" (gethash "arguments" fn))) clean)))
                    (let ((content (gethash "content" message)))
                      (unless (or (null content) (eq content :null) (stringp content))
                        (error "Activity assistant content is malformed"))
                      (push (obj "role" "assistant" "content" (or content :null)
                                 "tool_calls" (coerce (nreverse clean) 'vector)) messages))
                    (push id evidence)))))
             ((equal type "recursive-tool-result")
              (let* ((key (list (gethash "model_call_id" p) (gethash "tool_call_id" p)))
                     (entry (assoc key pending :test #'equal)))
                (unless (and entry (equal (second entry) (gethash "tool_name" p))
                             (stringp (gethash "content" p))
                             (member (gethash "execution_status" p)
                                     '("executed" "refused" "suppressed") :test #'equal))
                  (error "Activity tool result has no matching accepted call"))
                (setf pending (remove entry pending :test #'eq))
                (push (obj "role" "tool" "tool_call_id" (second key)
                           "content" (gethash "content" p)) messages)
                (push (obj "source_event_id" id "model_call_id" (first key)
                           "tool_call_id" (second key)
                           "execution_status" (gethash "execution_status" p)
                           "process_outcome" (gethash "process_outcome" p :null)) outcomes)
                (push id evidence)))
             ((equal type "agent-message")
              (unless (and (null pending) (stringp (gethash "text" p)))
                (error "Activity committed reply precedes tool settlement"))
              (push (obj "role" "assistant" "content" (gethash "text" p)) messages)
              (push id evidence) (setf finished t)))))))
    (unless started (error "Activity root is missing from supplied authority rows"))
    (obj "root_event_id" root "settled" (if finished t :false)
         "pending_tool_count" (length pending) "messages" (coerce (nreverse messages) 'vector)
         "source_event_ids" (coerce (nreverse evidence) 'vector)
         "tool_outcomes" (coerce (nreverse outcomes) 'vector))))

(defparameter *sustained-activity-compaction-policy* "ledger-working-index-v2")

(defun %sac-text-evidence (text event-id allowance)
  (let* ((size (length text)) (cut (> size allowance))
         (head (if cut (ceiling allowance 2) size)) (tail (if cut (floor allowance 2) 0)))
    (obj "source_event_id" event-id "original_characters" size
         "sha256" (ironclad:byte-array-to-hex-string
                   (ironclad:digest-sequence :sha256 (babel:string-to-octets text :encoding :utf-8)))
         "excerpted" (if cut t :false) "head" (subseq text 0 head)
         "tail" (if (plusp tail) (subseq text (- size tail)) "")
         "omitted_characters" (if cut (- size allowance) 0))))

(defun %sac-index-exchange (exchange allowance)
  (let* ((copy (%sac-copy exchange)) (messages (gethash "messages" exchange))
         (ids (gethash "source_event_ids" exchange))
         (text (with-output-to-string (out)
                 (format out "Historical execution index for root ~d. Excerpts are incomplete, not a semantic summary or current instructions. Retrieve originals with search-experience(event_id, offset).~%" (gethash "root_event_id" exchange))
                 (loop for i from 1 below (1- (length messages))
                       for message = (aref messages i) for id = (aref ids i)
                       do (format out "Event ~d: " id)
                          (if (equal "tool" (gethash "role" message))
                              (let ((outcome (find id (gethash "tool_outcomes" exchange) :key (lambda (item) (gethash "source_event_id" item)))))
                                (format out "result ~a; status ~a; process ~a~%" (gethash "tool_call_id" message) (gethash "execution_status" outcome) (shasht:write-json (gethash "process_outcome" outcome :null) nil)))
                              (loop for call across (gethash "tool_calls" message)
                                    do (format out "request ~a ~a; arguments at event ~d~%" (gethash "id" call) (gethash "name" (gethash "function" call)) id)))
                          (let ((content (gethash "content" message)))
                            (when (stringp content)
                              (let ((evidence (%sac-text-evidence content id allowance)))
                                (format out "sha256 ~a; omitted_characters ~d~%~a~%~a~%" (gethash "sha256" evidence) (gethash "omitted_characters" evidence) (gethash "head" evidence) (gethash "tail" evidence)))))))))
    (setf (gethash "representation" copy) "source-linked-execution-index"
          (gethash "compaction_policy" copy) *sustained-activity-compaction-policy*
          (gethash "excerpt_allowance" copy) allowance
          (gethash "messages" copy)
          (if (> (length messages) 2)
              (vector (%sac-copy (aref messages 0)) (obj "role" "user" "content" text)
                      (%sac-copy (aref messages (1- (length messages)))))
              (%sac-copy messages))) copy))

(defun %sac-exchanges-size (exchanges)
  (length (shasht:write-json (coerce (loop for e across exchanges append (coerce (gethash "messages" e) 'list)) 'vector) nil)))

(defun %sac-fit-exchanges (original maximum-characters complete-p
                           &key (trigger-ratio 4/5) (target-ratio 7/20)
                                (measure #'%sac-exchanges-size) force-p)
  (unless (and (realp trigger-ratio) (realp target-ratio)
               (< 0 target-ratio trigger-ratio) (<= trigger-ratio 1))
    (error "Working-context ratios must satisfy 0 < target < trigger <= 1"))
  (let* ((working (copy-seq original)) (original-size (funcall measure original))
         (size original-size) (target (floor (* maximum-characters target-ratio))))
    (when (and complete-p (or force-p (> size (* maximum-characters trigger-ratio))))
      (loop for index below (length original) while (> size target)
            unless (equal "holistic-summary-covered" (gethash "representation" (aref original index)))
            do (loop for allowance in '(4096 1024 256 0) while (> size target)
                     for candidate = (%sac-index-exchange (aref original index) allowance)
                     for trial = (let ((copy (copy-seq working))) (setf (aref copy index) candidate) copy)
                     for candidate-size = (funcall measure trial)
                     when (< candidate-size size) do (setf working trial size candidate-size))))
    (values working size original-size)))

(defun project-sustained-activity-context
    (reference events &key (maximum-characters 120000)
                          (trigger-ratio 4/5) (target-ratio 7/20) defer-budget-p)
  (let* ((activity (gethash "activity_id" reference)) (agent (gethash "agent_id" reference))
         (through (gethash "through_event_id" reference))
         (roots (%sac-array-list (gethash "root_event_ids" reference)))
         (rows (%sac-array-list events)) (by-root (make-hash-table :test #'eql))
         (seen (make-hash-table :test #'eql)) (root-order nil) (exchanges nil))
    (unless (and (stringp activity) (plusp (length activity)) (stringp agent) (plusp (length agent))
                 (integerp through) (plusp through) (<= 1 (length roots) 128) (<= (length rows) 4096)
                 (integerp maximum-characters) (<= 1 maximum-characters 1000000)
                 (= (length roots) (length (remove-duplicates roots)))
                 (every (lambda (root) (and (integerp root) (<= 1 root through))) roots))
      (error "Invalid sustained activity reference or projection bounds"))
    (dolist (event rows)
      (let ((id (gethash "id" event)))
        (unless (and (integerp id) (plusp id)) (error "Invalid activity event ID"))
        (when (and (<= id through) (equal agent (gethash "agent_id" event)))
          (let ((root (if (member id roots) id (gethash "caused_by" event))))
            (when (member root roots)
              (when (gethash id seen) (error "Duplicate activity authority row"))
              (setf (gethash id seen) t)
              (when (eql id root) (push root root-order))
              (push event (gethash root by-root)))))))
    (unless (equal roots (nreverse root-order))
      (error "Activity roots are missing or not in supplied authority order"))
    (dolist (root roots) (push (%sac-root-exchange root (nreverse (gethash root by-root))) exchanges))
    (let* ((original (coerce (nreverse exchanges) 'vector))
           (complete-p (every (lambda (e) (eq t (gethash "settled" e))) original)))
      (multiple-value-bind (working size original-size)
          (if defer-budget-p (let ((size (%sac-exchanges-size original))) (values original size size))
              (%sac-fit-exchanges original maximum-characters complete-p
                                  :trigger-ratio trigger-ratio :target-ratio target-ratio))
        (%sac-copy
         (obj "schema_version" 1 "activity_id" activity "agent_id" agent "through_event_id" through
              "status" (cond ((not complete-p) "incomplete")
                             ((and (not defer-budget-p) (> size maximum-characters)) "compaction-required")
                             (t "ready"))
              "exchanges" working "omitted_root_event_ids" #()
              "compacted_root_event_ids" (map 'vector (lambda (e) (gethash "root_event_id" e))
                                                   (remove-if-not (lambda (e) (gethash "compaction_policy" e)) working))
              "compaction_policy" *sustained-activity-compaction-policy*
              "original_characters" original-size "rendered_characters" size
              "maximum_characters" maximum-characters "budget_deferred" (if defer-budget-p t :false)
              "budget_unit" "serialized-native-history-characters"
              "trigger_characters" (floor (* maximum-characters trigger-ratio))
              "target_characters" (floor (* maximum-characters target-ratio))
              "target_reached" (if (<= size (* maximum-characters target-ratio)) t :false)
              "activity_completion" "not-assessed"))))))
