;;;; Synthetic-only lab context owner. Never a live identity/access adapter.
(in-package :pai.context-graph)

(defun lab-identity-step (graph row ordinal revision &optional descriptor-guide)
  (unless (and (%cg-closed-keys-p row '("episode" "calls"))
               (%cg-authority-array-p (gethash "calls" row) (if (%cgf-grouped-p) 14 13)))
    (%cg-authority-fail "LAB_IDENTITY_STEP_INVALID"))
  (multiple-value-bind (full boundary) (lab-authority-context graph (gethash "episode" row) ordinal)
    (unless (= 1 (length (%cgro-source-batches full)))
      (%cg-authority-fail "LAB_IDENTITY_MULTIBATCH_UNSUPPORTED"))
    (let ((calls (gethash "calls" row)) (index 0))
      (catch 'lab-identity-request
        (let ((envelope (%cgf-generate graph full 0 (context-graph-ontology graph) revision
                          (lambda (phase spec digest)
                            (when (= index (length calls))
                              (let ((result (%cg-authority-result "accepted" spec)))
                                (setf (gethash "phase" result) phase (gethash "request_digest" result) digest
                                      (gethash "terminal" result) :false)
                                (throw 'lab-identity-request result)))
                            (let ((saved (aref calls index))) (incf index)
                              (unless (and (%cg-closed-keys-p saved '("phase" "request_digest" "response"))
                                           (equal phase (gethash "phase" saved))
                                           (equal digest (gethash "request_digest" saved)))
                                (%cg-authority-fail "LAB_IDENTITY_RECEIPT_INVALID"))
                              (%cg-detach (gethash "response" saved)))) :descriptor-guide descriptor-guide)))
          (unless (= index (length calls)) (%cg-authority-fail "LAB_IDENTITY_EXTRA_RECEIPT"))
          (unless (equal "empty" (gethash "status" envelope))
            (setf (gethash "episode_id" boundary) (gethash "episode_id" (gethash "context" envelope))))
          (let ((result (%cgf-apply graph boundary full envelope :descriptor-guide descriptor-guide)))
            (setf (gethash "terminal" result) :true) result))))))

(defun lab-identity-session (bundle)
  ;; Deliberately synthetic-only: private historical sources need their own seal.
  (unless (and (equal "synthetic-controlled" (gethash "source_kind" bundle))
               (%cg-authority-array-p (gethash "history" bundle) 7)
               (%cg-authority-strings-p (gethash "queries" bundle) 32 1000)
               (%cg-authority-string-p (gethash "ontology_revision" bundle) 120)
               (member (gethash "retrieval_policy" bundle) '(nil "focused-kg-v1" "focused-kg-v2" "focused-kg-v3" "focused-kg-v4" "focused-kg-v5") :test #'equal))
    (%cg-authority-fail "LAB_SESSION_INVALID"))
  (let ((graph (make-context-graph (gethash "ontology" bundle))) (seen nil)
        (*cgf-protocol* (cond ((equal "identity-formation-v6-session" (gethash "authority_operation" bundle)) "identity-formation-v6")
                             ((equal "identity-formation-v5-session" (gethash "authority_operation" bundle)) "identity-formation-v5")
                             ((equal "identity-formation-v4-session" (gethash "authority_operation" bundle)) "identity-formation-v4")
                             ((equal "identity-formation-v3-session" (gethash "authority_operation" bundle)) "identity-formation-v3")
                             ((equal "identity-formation-v2-session" (gethash "authority_operation" bundle)) "identity-formation-v2")
                             (t "identity-formation-v1"))))
    (loop for row across (concatenate 'vector (gethash "history" bundle) (vector (gethash "step" bundle)))
          for ordinal from 0 for id = (gethash "case_id" (gethash "episode" row)) do
      (when (member id seen :test #'equal) (%cg-authority-fail "LAB_EPISODE_DUPLICATE"))
      (push id seen)
      (let ((result (lab-identity-step graph row ordinal (gethash "ontology_revision" bundle) (gethash "descriptor_guide" bundle))))
        (when (= ordinal (length (gethash "history" bundle)))
          (setf (gethash "queries" result)
                (if (context-graph-authority-profile graph)
                    (map 'vector (lambda (q) (%cg-authority-retrieve graph "lab-agent" "lab-persona" q
                      :lexicon (gethash "retrieval_lexicon" bundle
                                 (%cg-object "schema_version" 1 "entity_types" (make-hash-table :test #'equal)
                                             "predicates" (make-hash-table :test #'equal)))
                      :focused (not (null (gethash "retrieval_policy" bundle)))
                      :specific-relations (equal "focused-kg-v2" (gethash "retrieval_policy" bundle))
                      :query-specific-relations (not (null (member (gethash "retrieval_policy" bundle) '("focused-kg-v3" "focused-kg-v4" "focused-kg-v5") :test #'equal)))
                      :factual-entities (not (null (member (gethash "retrieval_policy" bundle) '("focused-kg-v3" "focused-kg-v4" "focused-kg-v5") :test #'equal))))) (gethash "queries" bundle)) #())
                (gethash "watermark" result) (%cg-authority-watermark graph "lab-agent" "lab-persona"))
          (return-from lab-identity-session result))
        (unless (eq :true (gethash "terminal" result)) (%cg-authority-fail "LAB_HISTORY_INCOMPLETE"))))))

(defun lab-authority-retrieval-session (bundle)
  "Replay sealed simple-model history; retrieve without changing its graph."
  (unless (and (equal "synthetic-controlled" (gethash "source_kind" bundle))
               (%cg-authority-array-p (gethash "history" bundle) 8 1)
               (%cg-authority-strings-p (gethash "queries" bundle) 32 1000)
               (member (gethash "retrieval_policy" bundle) '(nil "focused-kg-v1" "focused-kg-v2" "focused-kg-v3" "focused-kg-v4" "focused-kg-v5") :test #'equal))
    (%cg-authority-fail "LAB_SESSION_INVALID"))
  (let ((graph (make-context-graph (gethash "ontology" bundle))) (sources (make-hash-table :test #'equal)))
    (loop for row across (gethash "history" bundle) for n from 0 do
      (multiple-value-bind (context boundary) (lab-authority-context graph (gethash "episode" row) n)
        (declare (ignore boundary))
        (loop for source across (gethash "sources" (gethash "source_packet" context)) do
          (let ((prior (gethash (gethash "source_id" source) sources)))
            (when (and prior (not (%cg-authority-equal-p prior source))) (%cg-authority-fail "RETRIEVAL_SOURCE_INVALID"))
            (setf (gethash (gethash "source_id" source) sources) source))))
      (let ((result (lab-authority-step graph row n (gethash "ontology_revision" bundle) t)))
        (unless (and (equal "accepted" (gethash "status" result))
                     (equal "applied" (gethash "status" (gethash "application" (gethash "value" result)))))
          (%cg-authority-fail "LAB_HISTORY_INCOMPLETE"))))
    (let* ((before (%cg-authority-watermark graph "lab-agent" "lab-persona"))
           (packet (%cg-object "schema_version" 2 "sources"
                               (coerce (sort (loop for s being the hash-values of sources collect s)
                                             #'string< :key (lambda (s) (gethash "source_id" s))) 'vector)))
           (results (map 'vector (lambda (q) (%cg-authority-retrieve graph "lab-agent" "lab-persona" q
                                   :source-packet packet :lexicon (gethash "retrieval_lexicon" bundle)
                                   :focused (not (null (gethash "retrieval_policy" bundle)))
                                   :specific-relations (equal "focused-kg-v2" (gethash "retrieval_policy" bundle))
                                   :query-specific-relations (not (null (member (gethash "retrieval_policy" bundle) '("focused-kg-v3" "focused-kg-v4" "focused-kg-v5") :test #'equal)))
                                   :factual-entities (not (null (member (gethash "retrieval_policy" bundle) '("focused-kg-v3" "focused-kg-v4" "focused-kg-v5") :test #'equal))))) (gethash "queries" bundle))))
      (unless (%cg-authority-equal-p before (%cg-authority-watermark graph "lab-agent" "lab-persona"))
        (%cg-authority-fail "RETRIEVAL_MUTATED_GRAPH"))
      (%cg-authority-result "accepted" (%cg-object "queries" results "watermark" before)))))

(defun lab-authority-context (graph episode ordinal &optional source-reference-p)
  (unless (and (%cg-closed-keys-p episode '("case_id" "timestamp" "sources"))
               (%cg-authority-string-p (gethash "case_id" episode) 80)
               (integerp (gethash "timestamp" episode)) (plusp (gethash "timestamp" episode))
               (%cg-authority-array-p (gethash "sources" episode) 32 1))
    (%cg-authority-fail "LAB_EPISODE_INVALID"))
  (let* ((participants
           (map 'vector (lambda (role kind)
                          (%cg-object "role" role "speaker_id" (concatenate 'string "lab-principal:" role) "principal_id" (concatenate 'string "lab-principal:" role)
                                      "identity_binding_id" (concatenate 'string "lab-binding:" role)
                                      "local_ref" (concatenate 'string "runtime:" role) "entity_id" (concatenate 'string "lab-entity:" role)
                                      "kind" kind "label" role "aliases" #()))
                #("operator" "active-persona") #("person" "agent")))
         (sources
           (map 'vector (lambda (source)
                          (unless (and (%cg-closed-keys-p source '("source_id" "speaker_id" "kind" "text"))
                                       (%cg-authority-string-p (gethash "source_id" source) 180)
                                       (%cg-authority-string-p (gethash "text" source) 12000))
                            (%cg-authority-fail "LAB_SOURCE_INVALID"))
                          (let* ((role (gethash "speaker_id" source))
                                 (participant (find role participants :test #'equal :key (lambda (p) (gethash "role" p)))))
                            (unless (and participant (equal (gethash "kind" source)
                                                            (if (equal role "operator") "original-utterance" "prior-agent-utterance")))
                              (%cg-authority-fail "LAB_SOURCE_IDENTITY_INVALID"))
                            (%cg-object "source_id" (gethash "source_id" source) "speaker_id" (gethash "principal_id" participant) "kind" (gethash "kind" source)
                                        "timestamp" (gethash "timestamp" episode) "text" (gethash "text" source)
                                        "text_sha256" (%cg-sha256 (gethash "text" source))
                                        "identity" (%cg-object "principal_id" (gethash "principal_id" participant)
                                                               "binding_id" (gethash "identity_binding_id" participant)
                                                               "conversation_id" "lab-conversation" "role" role)
                                        "resource_ref" (%cg-object "store" "artifact" "resource_id" (gethash "source_id" source)
                                                                   "version_id" (%cg-sha256 (gethash "text" source)) "component" "content"))))
                (gethash "sources" episode)))
         (policy (%cg-object "policy_revision" "operator-conversational-label-correction-v1" "enabled" :true
                             "scope_definitions" (vector (%cg-object "definition_id" "operator-organisms" "predicate" "owns"
                                                                     "operator_endpoint" "subject" "target_kind" "organism"))))
         (partition (%cg-authority-partition-view graph "lab-agent" "lab-persona" "lab-entity:operator"))
         (scoped (gethash "value" (context-graph-build-correction-scopes partition policy participants)))
         (eligible (coerce (gethash "eligible_entities" scoped) 'list))
         (ids (context-graph-entity-scan-index graph)) (examined (min 64 (length ids))))
    ;; Scope candidates are mandatory; ordinary candidates use the remaining
    ;; bounded slots. No name ranking or Python-selected identity authority.
    (dotimes (i examined)
      (let ((entity (gethash (aref ids i) (context-graph-entities graph))))
        (when (and (< (length eligible) 64) (eq :null (gethash "participant_role" entity)))
          (pushnew entity eligible :test #'equal :key (lambda (e) (gethash "entity_id" e))))))
    (values
     (funcall (if source-reference-p #'context-graph-enable-source-reference-corrections #'identity)
     (%cg-object "schema_version" 1 "authority_revision" "context-graph-authority-v1"
                 "agent_id" "lab-agent" "persona_id" "lab-persona" "episode_id" (gethash "case_id" episode)
                 "source_packet" (%cg-object "schema_version" 2 "sources" sources)
                 "primary_source_ids" (map 'vector (lambda (s) (gethash "source_id" s)) sources)
                 "access_context" (%cg-object "schema_version" 1 "executor_principal_id" "lab-principal:active-persona"
                                              "authority_principal_id" "lab-principal:operator" "recipient_principal_id" :null
                                              "recipient_binding_id" :null "recipient_set_digest" :null "task_id" :null
                                              "purpose" "private-planning" "channel_id" "private-runtime" "action" "derive"
                                              "partition" (%cg-object "agent_id" "lab-agent" "persona_id" "lab-persona")
                                              "grant_ids" #() "now_utc" (gethash "timestamp" episode) "policy_epoch" 1)
                 "access_snapshot_digest" (%cg-sha256 "synthetic-only-not-live-authorization")
                 "projection_watermark" (gethash "projection_watermark" partition) "correction_policy" policy
                 "correction_scopes" (gethash "scopes" scoped) "participants" participants
                 "eligible_entities" (coerce (sort eligible #'string< :key (lambda (e) (gethash "entity_id" e))) 'vector)
                 "operator_commands" #() "candidate_scan" (%cg-object "complete" (if (= examined (length ids)) :true :false) "examined_count" examined)))
     (%cg-object "episode_id" (gethash "case_id" episode) "opened_boundary_id" (1+ (* ordinal 2))
                 "application_event_id" (+ 2 (* ordinal 2)) "observed_at" (gethash "timestamp" episode)))))

(defun lab-authority-step (graph row ordinal ontology-revision &optional simple-p source-reference-p)
  (when (eq simple-p :staged)
    (return-from lab-authority-step (lab-staged-step graph row ordinal ontology-revision source-reference-p)))
  (unless (%cg-closed-keys-p row '("episode" "proposal" "review" "request_digest"))
    (%cg-authority-fail "LAB_STEP_INVALID"))
  (multiple-value-bind (context boundary) (lab-authority-context graph (gethash "episode" row) ordinal source-reference-p)
    (when (and simple-p (not (eq :null (gethash "proposal" row))))
      (setf row (%cg-detach row)
            (gethash "proposal" row) (funcall (if (eq simple-p :correction) #'%cgt-correction-expand #'%cgs-expand)
                                             context (context-graph-ontology graph) ontology-revision (gethash "proposal" row))))
    (unless (eq :null (gethash "proposal" row))
      (let ((validated (%cgm-validate-ontology context (gethash "proposal" row) (context-graph-ontology graph) ontology-revision)))
        (unless (equal "accepted" (gethash "status" validated)) (return-from lab-authority-step validated))))
    (cond ((eq :null (gethash "proposal" row))
           (if simple-p (funcall (if (eq simple-p :correction) #'%cgt-correction-input #'%cgs-extraction-input)
                                context (context-graph-ontology graph) ontology-revision)
               (%cgm-extraction-input context (context-graph-ontology graph) ontology-revision)))
          ((eq :null (gethash "review" row))
           (let ((built (%cgm-review-input context (gethash "proposal" row) ontology-revision)))
             (when (equal "accepted" (gethash "status" built))
               (setf (gethash "request_digest" built) (%cg-authority-digest "model-review-input" (gethash "value" built)))) built))
          (t (%cgm-apply-reviewed graph boundary context (gethash "proposal" row) (gethash "review" row) ontology-revision
                                  (%cg-object "request_digest" (gethash "request_digest" row)
                                              "response_digest" (%cg-authority-digest "model-review-output" (gethash "review" row))))))))

(defun lab-staged-step (graph row ordinal revision &optional source-reference-p)
  (unless (%cg-closed-keys-p row '("episode" "entity_selection" "entity_request_digest" "proposal" "fact_request_digest" "review" "request_digest"))
    (%cg-authority-fail "STAGED_STEP_INVALID"))
  (multiple-value-bind (context boundary) (lab-authority-context graph (gethash "episode" row) ordinal source-reference-p)
    (declare (ignore boundary))
    (let* ((ontology (context-graph-ontology graph))
           (selection (gethash "entity_selection" row))
           (entities (%cgt-entity-input context ontology revision))
           (entity-digest (%cg-authority-digest "staged-entity-input-v1"
                                              (%cg-object "context" context "spec" (gethash "value" entities)))))
      (when (eq selection :null)
        (unless (every (lambda (key) (eq :null (gethash key row)))
                       '("entity_request_digest" "proposal" "fact_request_digest" "review" "request_digest"))
          (%cg-authority-fail "STAGED_ORDER_INVALID"))
        (setf (gethash "request_digest" entities) entity-digest)
        (return-from lab-staged-step entities))
      (unless (equal entity-digest (gethash "entity_request_digest" row))
        (%cg-authority-fail "STAGED_ENTITY_BINDING_INVALID"))
      (let* ((facts (%cgt-fact-input context ontology revision selection))
             (fact-digest (%cg-authority-digest "staged-fact-input-v1"
                                              (%cg-object "context" context "spec" (gethash "value" facts)))))
        (when (eq :null (gethash "proposal" row))
          (unless (every (lambda (key) (eq :null (gethash key row))) '("fact_request_digest" "review" "request_digest"))
            (%cg-authority-fail "STAGED_ORDER_INVALID"))
          (setf (gethash "request_digest" facts) fact-digest)
          (return-from lab-staged-step facts))
        (unless (equal fact-digest (gethash "fact_request_digest" row))
          (%cg-authority-fail "STAGED_FACT_BINDING_INVALID"))
        (lab-authority-step graph
          (%cg-object "episode" (gethash "episode" row)
                      "proposal" (%cgt-combine context ontology selection (gethash "proposal" row))
                      "review" (gethash "review" row) "request_digest" (gethash "request_digest" row))
          ordinal revision t source-reference-p)))))

(defun lab-authority-input-result (thunk)
  "Report declared input refusals without concealing unexpected runtime errors."
  (handler-case (funcall thunk)
    (context-graph-authority-input-error (condition)
      (%cg-authority-result "rejected" nil (%cg-authority-error-code condition)))))

(defun lab-authority-session (bundle &optional simple-p source-reference-p)
  (unless (and (equal "synthetic-controlled" (gethash "source_kind" bundle))
               (%cg-authority-array-p (gethash "history" bundle) 7)
               (%cg-authority-strings-p (gethash "queries" bundle) 32 1000)
               (%cg-authority-string-p (gethash "ontology_revision" bundle) 180))
    (%cg-authority-fail "LAB_SESSION_INVALID"))
  (let ((graph (make-context-graph (gethash "ontology" bundle))) (seen nil))
    (loop for row across (concatenate 'vector (gethash "history" bundle) (vector (gethash "step" bundle))) for ordinal from 0
          for id = (gethash "case_id" (gethash "episode" row))
          do (when (member id seen :test #'equal) (%cg-authority-fail "LAB_EPISODE_DUPLICATE")) (push id seen)
             (let ((result (lab-authority-step graph row ordinal (gethash "ontology_revision" bundle)
                                              (if (and (eq simple-p :correction) (< ordinal (length (gethash "history" bundle)))) t simple-p)
                                              source-reference-p)))
               (when (= ordinal (length (gethash "history" bundle)))
                 (setf (gethash "queries" result)
                       (if (context-graph-authority-profile graph)
                           (map 'vector (lambda (q) (%cg-authority-search graph "lab-agent" "lab-persona" q)) (gethash "queries" bundle)) #())
                       (gethash "watermark" result) (%cg-authority-watermark graph "lab-agent" "lab-persona"))
                 (return-from lab-authority-session result))
               (unless (and (not (eq :null (gethash "proposal" row))) (not (eq :null (gethash "review" row)))
                            (member (gethash "status" result) '("accepted" "rejected") :test #'equal))
                 (%cg-authority-fail "LAB_HISTORY_INCOMPLETE"))))))
